"""State module - State composed of multiple Intents.

State represents a state composed of multiple Intent units.
"""

import uuid
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field
from pydantic import model_validator


class StateType(Enum):
    """Enumeration of state types.

    Defines all possible semantic state types, categorized by function.
    """

    # Browsing
    BROWSE_CATALOG = 'BrowseCatalog'
    BROWSE_PRODUCT = 'BrowseProduct'
    BROWSE_SEARCH_RESULTS = 'BrowseSearchResults'
    BROWSE_PAGE = 'BrowsePage'

    # Information Extraction
    INSPECT_PRODUCT_PRICE = 'InspectProductPrice'
    INSPECT_PRODUCT_DETAILS = 'InspectProductDetails'
    EXTRACT_PRODUCT_INFO = 'ExtractProductInfo'
    EXTRACT_TEXT = 'ExtractText'

    # Comparison & Decision
    COMPARE_PRODUCTS = 'CompareProducts'
    COMPARE_PRICES = 'ComparePrices'
    EVALUATE_OPTIONS = 'EvaluateOptions'

    # Search
    SEARCH_PRODUCTS = 'SearchProducts'
    SEARCH_CONTENT = 'SearchContent'
    FILTER_RESULTS = 'FilterResults'
    SORT_RESULTS = 'SortResults'

    # Selection & Action
    SELECT_PRODUCT = 'SelectProduct'
    ADD_TO_CART = 'AddToCart'
    ADD_TO_WISHLIST = 'AddToWishlist'
    REMOVE_FROM_CART = 'RemoveFromCart'

    # Navigation
    NAVIGATE_CATEGORY = 'NavigateCategory'
    NAVIGATE_TO_PAGE = 'NavigateToPage'
    GO_TO_HOMEPAGE = 'GoToHomepage'
    GO_BACK = 'GoBack'

    # Interaction
    FILL_FORM = 'FillForm'
    SUBMIT_FORM = 'SubmitForm'
    LOGIN = 'Login'
    LOGOUT = 'Logout'

    # Content Operations
    COPY_CONTENT = 'CopyContent'
    PASTE_CONTENT = 'PasteContent'
    EDIT_TEXT = 'EditText'

    # Other types
    UNKNOWN = 'Unknown'
    LLM_GENERATED = 'LLMGenerated'  # LLM-generated custom type


class State(BaseModel):
    """State - State composed of multiple Intents.

    Represents a state composed of multiple Intent units.
    This is a node unit in the memory graph, representing a complete
    user behavioral intent.

    Attributes:
        id: Unique state identifier (auto-generated if not provided).
        label: Semantic label.
        type: State type.
        timestamp: State start timestamp in milliseconds.
        end_timestamp: State end timestamp in milliseconds (optional).
        duration: Duration in milliseconds (optional).
        page_url: Associated page URL.
        page_title: Page title (optional).
        user_id: User ID (optional).
        session_id: Session ID (optional).
        goal_id: Associated user goal ID (optional).
        phase: Cognitive phase (optional).
        atomic_intents: List of contained Intents.
        atomic_intent_ids: List of Intent IDs (optional).
        attributes: Semantic attributes.
        embedding_vector: Vector representation for retrieval (optional).
        llm_generated: Whether generated by LLM.
        confidence_score: Confidence score (optional).
    """

    # Core identifiers
    id: Optional[str] = Field(
        default=None, description='Unique state identifier')
    label: str = Field(..., description='Semantic label')
    type: StateType = Field(..., description='State type')

    # Time information
    timestamp: int = Field(
        ..., description='State start timestamp in milliseconds')
    end_timestamp: Optional[int] = Field(
        default=None, description='State end timestamp in milliseconds')
    duration: Optional[int] = Field(
        default=None, description='Duration in milliseconds')

    # Page information
    page_url: str = Field(..., description='Associated page URL')
    page_title: Optional[str] = Field(default=None, description='Page title')

    # User session information
    user_id: Optional[str] = Field(default=None, description='User ID')
    session_id: Optional[str] = Field(default=None, description='Session ID')

    # Association information
    goal_id: Optional[str] = Field(
        default=None, description='Associated user goal ID')
    phase: Optional[str] = Field(default=None, description='Cognitive phase')

    # Contained atomic intents
    atomic_intents: List[Any] = Field(
        default_factory=list, description='List of contained Intents')
    atomic_intent_ids: Optional[List[str]] = Field(
        default=None, description='List of Intent IDs')

    # Semantic attributes
    attributes: Dict[str, Any] = Field(
        default_factory=dict, description='Semantic attributes')

    # Vector representation (for retrieval)
    embedding_vector: Optional[List[float]] = Field(
        default=None, description='Vector representation')

    # LLM related
    llm_generated: bool = Field(
        default=False, description='Whether generated by LLM')
    confidence_score: Optional[float] = Field(
        default=None, description='Confidence score', ge=0.0, le=1.0)

    @model_validator(mode='before')
    @classmethod
    def generate_id(cls, data: Any) -> Any:
        """Auto-generate ID if not provided.

        Args:
            data: Input data dictionary.

        Returns:
            Data with ID generated if missing.
        """
        if isinstance(data, dict):
            if not data.get('id'):
                data['id'] = str(uuid.uuid4())
        return data

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary.

        Returns:
            Dictionary representation of the state.
        """
        data = self.model_dump()
        data['type'] = self.type.value
        # Handle atomic_intents
        if self.atomic_intents:
            data['atomic_intents'] = [
                intent.to_dict() if hasattr(intent, 'to_dict') else intent
                for intent in self.atomic_intents
            ]
        return data

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'State':
        """Create instance from dictionary.

        Args:
            data: Dictionary containing state data.

        Returns:
            State instance.
        """
        if isinstance(data.get('type'), str):
            data['type'] = StateType(data['type'])
        return cls(**data)


# Backward compatibility aliases
SemanticState = State
SemanticStateType = StateType


__all__ = [
    'State',
    'StateType',
    'SemanticState',  # Backward compatibility
    'SemanticStateType',  # Backward compatibility
]
