"""Script Templates for Claude Agent SDK

These templates are used by Claude Agent to generate scripts.
They provide structure and helper functions that Claude fills in.
"""

# =============================================================================
# Browser Script Templates
# =============================================================================

BROWSER_TEST_OPERATION = '''#!/usr/bin/env python3
"""Test script - Validates that find_element.py correctly finds the target element.

This script:
1. Loads DOM data from dom_data.json
2. Calls find_target_element() from find_element.py
3. Validates the returned interactive_index exists in selector_map
4. Reports success or failure with details

Usage: python test_operation.py
Exit code: 0 = success, 1 = failure
"""
import json
import sys

def test():
    """Test find_element.py and validate result"""
    # Load DOM (wrapped format: {"url": ..., "dom": {...}})
    try:
        with open("dom_data.json", "r", encoding="utf-8") as f:
            data = json.load(f)
        if "dom" not in data:
            print("FAILED: Invalid DOM format - missing 'dom' key")
            return False
        dom_dict = data["dom"]
    except Exception as e:
        print(f"FAILED: Cannot load dom_data.json: {e}")
        return False

    # Load task info
    try:
        with open("task.json", "r", encoding="utf-8") as f:
            task_info = json.load(f)
    except Exception as e:
        print(f"FAILED: Cannot load task.json: {e}")
        return False

    # Import and run find_element
    try:
        from find_element import find_target_element
    except ImportError as e:
        print(f"FAILED: Cannot import find_element.py: {e}")
        return False
    except SyntaxError as e:
        print(f"FAILED: Syntax error in find_element.py: {e}")
        return False

    # Execute find_target_element
    try:
        result = find_target_element(dom_dict)
    except Exception as e:
        print(f"FAILED: find_target_element() raised exception: {e}")
        import traceback
        traceback.print_exc()
        return False

    # Validate result structure
    if not isinstance(result, dict):
        print(f"FAILED: find_target_element() must return dict, got {type(result)}")
        return False

    if not result.get("success"):
        error = result.get("error", "Unknown error")
        print(f"FAILED: find_target_element() returned failure: {error}")
        return False

    # Validate interactive_index
    interactive_index = result.get("interactive_index")
    if interactive_index is None:
        print("FAILED: Result missing 'interactive_index'")
        return False

    if not isinstance(interactive_index, int):
        print(f"FAILED: interactive_index must be int, got {type(interactive_index)}")
        return False

    # Validate element_info
    element_info = result.get("element_info", {})
    if not element_info:
        print("WARNING: Result missing 'element_info', but interactive_index is valid")

    # Success!
    print(f"SUCCESS: Found element")
    print(f"  interactive_index: {interactive_index}")
    print(f"  tag: {element_info.get('tag', 'N/A')}")
    print(f"  text: {element_info.get('text', 'N/A')[:50] if element_info.get('text') else 'N/A'}")
    print(f"  class: {element_info.get('class', 'N/A')[:50] if element_info.get('class') else 'N/A'}")
    return True

if __name__ == "__main__":
    success = test()
    sys.exit(0 if success else 1)
'''


BROWSER_FIND_ELEMENT_TEMPLATE = '''#!/usr/bin/env python3
"""Find target element in DOM - Generated by Claude Agent

This script finds the target element based on task description and xpath hints.
It searches dom_data.json and returns the interactive_index of the target element.

IMPORTANT:
- Only elements with 'interactive_index' can be clicked or filled
- For input fields, prefer div with 'EditorClass' over hidden inputs
- Handle both Chinese and English text (e.g., "新邮件" = "New mail")
"""
import json
from typing import Dict, Optional, List

def find_target_element(dom_dict: dict) -> dict:
    """Find target element and return its interactive_index

    Args:
        dom_dict: DOM dictionary loaded from dom_data.json

    Returns:
        dict with:
        - success: bool
        - interactive_index: int (element index for click/fill operations)
        - element_info: dict with tag, text, xpath, class (for debugging)
        - error: str (if success is False)
    """

    def search_recursive(node: dict, condition_fn) -> Optional[dict]:
        """Recursively search DOM tree with a condition function"""
        if condition_fn(node):
            return node
        for child in node.get('children', []):
            result = search_recursive(child, condition_fn)
            if result:
                return result
        return None

    def search_by_text(node: dict, keywords: List[str], require_interactive: bool = True) -> Optional[dict]:
        """Search for element containing any of the keywords in text"""
        def condition(n):
            text = (n.get('text', '') or '').lower()
            has_index = n.get('interactive_index') is not None
            for kw in keywords:
                if kw.lower() in text:
                    if not require_interactive or has_index:
                        return True
            return False
        return search_recursive(node, condition)

    def search_by_class(node: dict, class_keywords: List[str]) -> Optional[dict]:
        """Search for element with class containing any keyword"""
        def condition(n):
            cls = (n.get('class', '') or '').lower()
            has_index = n.get('interactive_index') is not None
            for kw in class_keywords:
                if kw.lower() in cls and has_index:
                    return True
            return False
        return search_recursive(node, condition)

    def search_by_placeholder(node: dict, keywords: List[str]) -> Optional[dict]:
        """Search input by placeholder text"""
        def condition(n):
            placeholder = (n.get('placeholder', '') or '').lower()
            has_index = n.get('interactive_index') is not None
            for kw in keywords:
                if kw.lower() in placeholder and has_index:
                    return True
            return False
        return search_recursive(node, condition)

    def search_by_aria_label(node: dict, keywords: List[str]) -> Optional[dict]:
        """Search by aria-label attribute"""
        def condition(n):
            aria = (n.get('aria-label', '') or '').lower()
            has_index = n.get('interactive_index') is not None
            for kw in keywords:
                if kw.lower() in aria and has_index:
                    return True
            return False
        return search_recursive(node, condition)

    # TODO: Implement your search logic here based on task.json
    # Example searches (uncomment and modify as needed):
    #
    # element = search_by_text(dom_dict, ["New mail", "新邮件"])
    # element = search_by_class(dom_dict, ["EditorClass"])
    # element = search_by_placeholder(dom_dict, ["Subject", "主题"])
    # element = search_by_aria_label(dom_dict, ["New message"])

    element = None  # Replace with actual search

    # Return result
    if not element:
        return {"success": False, "error": "Target element not found in DOM"}

    if element.get('interactive_index') is None:
        return {"success": False, "error": "Found element but it has no interactive_index (not clickable)"}

    return {
        "success": True,
        "interactive_index": element.get("interactive_index"),
        "element_info": {
            "tag": element.get("tag"),
            "text": (element.get("text") or "")[:100],
            "xpath": element.get("xpath"),
            "class": element.get("class")
        }
    }

if __name__ == "__main__":
    # Test locally - DOM files use wrapped format: {"url": ..., "dom": {...}}
    with open("dom_data.json", "r", encoding="utf-8") as f:
        data = json.load(f)
    if "dom" not in data:
        raise ValueError("Invalid DOM format: missing 'dom' key")
    result = find_target_element(data["dom"])
    print(json.dumps(result, indent=2, ensure_ascii=False))
'''


# =============================================================================
# Claude Agent Prompts
# =============================================================================

BROWSER_AGENT_PROMPT = """# Browser Element Finder Task

## Your Working Directory
You are working in: `{working_dir}`

## Available Files
- `dom_data.json` - Current page DOM structure (nested JSON)
- `find_element_template.py` - Template with helper functions (copy and modify)
- `test_operation.py` - Test script to validate your find_element.py

## Your Task
Create `find_element.py` that finds the target element.
{task_details}

## Available Skills

**IMPORTANT**: Read the skill SKILL.md file first for detailed guidance:
```bash
cat .claude/skills/element-finder/SKILL.md
```

**Element Tools** - Use these to find elements BEFORE writing script:
```bash
# Analyze xpath hint from recording (RECOMMENDED FIRST STEP)
python .claude/skills/element-finder/tools/element_tools.py hint "<xpath_hint>"

# Search by text keyword (searches text, aria-label, placeholder)
python .claude/skills/element-finder/tools/element_tools.py search "Submit"

# Find element by xpath, check if it has interactive_index
python .claude/skills/element-finder/tools/element_tools.py find "<xpath>"

# List all interactive elements in a container
python .claude/skills/element-finder/tools/element_tools.py list "<container_xpath>"

# Search by specific attribute
python .claude/skills/element-finder/tools/element_tools.py attr "aria-label" "Send message"
```

## Instructions

### Step 1: Use Element Tools
Use the element tools to find the target element:
```bash
# First, try the hint command with xpath hint above
python .claude/skills/element-finder/tools/element_tools.py hint "<xpath_hint>"

# If hint fails, search by text keywords
python .claude/skills/element-finder/tools/element_tools.py search "<keyword>"
```

### Step 2: Create find_element.py
Copy the template and implement the search logic based on what tools found:
```bash
cp find_element_template.py find_element.py
```
Then edit find_element.py to implement the actual search.

### Step 3: Test
Run the test script to verify your implementation:
```bash
python test_operation.py
```
If it fails, read the error and fix find_element.py.

## DOM Element Structure
Each element in dom_data.json contains:
- `tag`: HTML tag (button, input, div, etc.)
- `text`: Text content
- `xpath`: XPath location
- `interactive_index`: **REQUIRED** - Index for click/fill operations
- `class`, `id`, `placeholder`, `aria-label`: HTML attributes
- `children`: Child elements

## CRITICAL Rules
1. Only elements with `interactive_index` can be clicked or filled
2. For input fields: prefer `div` with `EditorClass` over hidden `input`
3. Handle multi-language: "新邮件" = "New mail", "添加主题" = "Add subject"
4. Return `interactive_index` as an integer

## XPath Quote Normalization

**IMPORTANT**: xpath_hints may use single quotes (`'`), but dom_data.json uses double quotes (`"`).

When matching xpath, always normalize quotes:
```python
def normalize_xpath(xpath: str) -> str:
    return xpath.replace("'", '"')

# When comparing:
if normalize_xpath(node.get('xpath', '')) == normalize_xpath(target_xpath):
    return node
```

## Success Criteria
`python test_operation.py` must print "SUCCESS" and exit with code 0.
"""


SCRAPER_AGENT_PROMPT = """# Data Extraction Script Generation

Generate `extraction_script.py` to extract data from the webpage DOM.

## Task Context

- **Working Directory**: `{working_dir}`
- **Page URL**: `{page_url}`

## Extraction Requirements

**User Description**: {user_description}

**Output Format (fields to extract)**:
{fields_description}
{sample_description}
{xpath_hints_description}

## Input Files

- `dom_data.json` - Page DOM as nested JSON dictionary

## DOM Tools

`dom_tools.py` is available in the current directory.

| Command | Purpose | Output |
|---------|---------|--------|
| `find <xpath>` or `find <json>` | Multi-field extraction | value + children + siblings |
| `container <xpath> --fields ...` | List extraction | List items array |
| `search --text/--class` | Search elements | Matching elements list |

**IMPORTANT**: Read `.claude/skills/dom-extraction/SKILL.md` for detailed workflow.

## Workflow

### Step 1: Determine Extraction Type
- **List** ("all", "every", "list") → Use `container` command
- **Multi-field** (detail page) → Use `find` with JSON

### Step 2: Execute Based on Type

**For List Extraction (one step):**
```bash
python dom_tools.py container "//*[@id='app']/div[4]/div/a[1]" --fields "name:text,url:href"
```
Container auto-finds parent. Use the output code snippet directly.

**For Multi-field Extraction:**
```bash
python dom_tools.py find '{{"name": "<xpath1>", "rating": "<xpath2>", "description": "<xpath3>"}}'
```

The `find` command returns for each xpath:
- **value**: The extracted text/href
- **children**: If container, shows all child elements with xpath + text
- **siblings**: Shows sibling elements

**Analyze the output:**
- If xpath is a **container** (shows children) → use the child xpath for specific value
- If xpath has **siblings** → decide if content needs merging
- If xpath **not found** → use `search` command

### Step 3: If xpath fails, search
```bash
python dom_tools.py search --text "9.0"
python dom_tools.py search --class "rating"
```

### Step 4: Write Script
Use corrected xpaths based on `find` output:
```python
from dom_tools import extract_list, extract_single, extract_multi
```

### Step 5: Test
```bash
python extraction_script.py
```

## CRITICAL Rules

1. **Use dom_tools functions** - Don't write custom xpath search logic.

2. **Trust `find` output** - If it shows children, use the child xpath. If it shows siblings, consider merging.

3. **URLs MUST be absolute** - Use `make_absolute(url, page_url)` to convert relative URLs.

4. **Respect xpath indices** - `div[4]` means the 4th div. Extract from that specific container.

5. **page_url parameter** - The function receives `page_url` as second parameter. Use it for URL conversion or return it directly if needed.

## Required Script Format

Your `extraction_script.py` MUST follow this exact structure:

```python
import json
from typing import Dict, List
from urllib.parse import urljoin

from dom_tools import extract_list, extract_single, extract_multi


def make_absolute(url: str, page_url: str) -> str:
    \"\"\"Convert relative URL to absolute URL\"\"\"
    if not url or url.startswith(('http://', 'https://')):
        return url
    return urljoin(page_url, url)


def extract_data_from_page(dom_dict: Dict, page_url: str = "") -> List[Dict]:
    \"\"\"Extract data from DOM dictionary.

    Args:
        dom_dict: The page DOM as a nested dictionary
        page_url: Current page URL (use for make_absolute or return directly)

    Returns:
        List of extracted data dictionaries
    \"\"\"
    # YOUR EXTRACTION LOGIC HERE
    # Use extract_list, extract_single, or extract_multi from dom_tools
    results = []

    # Make URLs absolute using page_url parameter
    for item in results:
        if 'url' in item:
            item['url'] = make_absolute(item['url'], page_url)

    return results


# Main entry point - reads dom_data.json and calls extract function
if __name__ == "__main__":
    with open("dom_data.json", "r") as f:
        data = json.load(f)
    # DOM files use wrapped format: {{"url": ..., "dom": {{...}}}}
    if "dom" not in data:
        raise ValueError("Invalid DOM format: missing 'dom' key. Expected wrapped format.")
    page_url = data.get("url", "")
    results = extract_data_from_page(data["dom"], page_url)
    print(json.dumps(results, indent=2, ensure_ascii=False))
```

**IMPORTANT**:
- `extract_data_from_page(dom_dict, page_url)` receives both DOM and current page URL
- Use `page_url` parameter to convert relative URLs via `make_absolute(url, page_url)`
- You can also return `page_url` directly if the user wants the current page URL as output
- File reading (`dom_data.json`) only happens in `if __name__ == "__main__":` block for testing
- DOM files use wrapped format: `{{"url": "...", "dom": {{...}}}}`
"""
