"""Script Templates for Claude Agent SDK

These templates are used by Claude Agent to generate scripts.
They provide structure and helper functions that Claude fills in.
"""

# =============================================================================
# Browser Script Templates
# =============================================================================

BROWSER_TEST_OPERATION = '''#!/usr/bin/env python3
"""Test script - Validates that find_element.py correctly finds the target element.

This script:
1. Loads DOM data from dom_data.json
2. Calls find_target_element() from find_element.py
3. Validates the returned interactive_index exists in selector_map
4. Reports success or failure with details

Usage: python test_operation.py
Exit code: 0 = success, 1 = failure
"""
import json
import sys

def test():
    """Test find_element.py and validate result"""
    # Load DOM
    try:
        with open("dom_data.json", "r", encoding="utf-8") as f:
            dom_dict = json.load(f)
    except Exception as e:
        print(f"FAILED: Cannot load dom_data.json: {e}")
        return False

    # Load task info
    try:
        with open("task.json", "r", encoding="utf-8") as f:
            task_info = json.load(f)
    except Exception as e:
        print(f"FAILED: Cannot load task.json: {e}")
        return False

    # Import and run find_element
    try:
        from find_element import find_target_element
    except ImportError as e:
        print(f"FAILED: Cannot import find_element.py: {e}")
        return False
    except SyntaxError as e:
        print(f"FAILED: Syntax error in find_element.py: {e}")
        return False

    # Execute find_target_element
    try:
        result = find_target_element(dom_dict)
    except Exception as e:
        print(f"FAILED: find_target_element() raised exception: {e}")
        import traceback
        traceback.print_exc()
        return False

    # Validate result structure
    if not isinstance(result, dict):
        print(f"FAILED: find_target_element() must return dict, got {type(result)}")
        return False

    if not result.get("success"):
        error = result.get("error", "Unknown error")
        print(f"FAILED: find_target_element() returned failure: {error}")
        return False

    # Validate interactive_index
    interactive_index = result.get("interactive_index")
    if interactive_index is None:
        print("FAILED: Result missing 'interactive_index'")
        return False

    if not isinstance(interactive_index, int):
        print(f"FAILED: interactive_index must be int, got {type(interactive_index)}")
        return False

    # Validate element_info
    element_info = result.get("element_info", {})
    if not element_info:
        print("WARNING: Result missing 'element_info', but interactive_index is valid")

    # Success!
    print(f"SUCCESS: Found element")
    print(f"  interactive_index: {interactive_index}")
    print(f"  tag: {element_info.get('tag', 'N/A')}")
    print(f"  text: {element_info.get('text', 'N/A')[:50] if element_info.get('text') else 'N/A'}")
    print(f"  class: {element_info.get('class', 'N/A')[:50] if element_info.get('class') else 'N/A'}")
    return True

if __name__ == "__main__":
    success = test()
    sys.exit(0 if success else 1)
'''


BROWSER_FIND_ELEMENT_TEMPLATE = '''#!/usr/bin/env python3
"""Find target element in DOM - Generated by Claude Agent

This script finds the target element based on task description and xpath hints.
It searches dom_data.json and returns the interactive_index of the target element.

IMPORTANT:
- Only elements with 'interactive_index' can be clicked or filled
- For input fields, prefer div with 'EditorClass' over hidden inputs
- Handle both Chinese and English text (e.g., "新邮件" = "New mail")
"""
import json
from typing import Dict, Optional, List

def find_target_element(dom_dict: dict) -> dict:
    """Find target element and return its interactive_index

    Args:
        dom_dict: DOM dictionary loaded from dom_data.json

    Returns:
        dict with:
        - success: bool
        - interactive_index: int (element index for click/fill operations)
        - element_info: dict with tag, text, xpath, class (for debugging)
        - error: str (if success is False)
    """

    def search_recursive(node: dict, condition_fn) -> Optional[dict]:
        """Recursively search DOM tree with a condition function"""
        if condition_fn(node):
            return node
        for child in node.get('children', []):
            result = search_recursive(child, condition_fn)
            if result:
                return result
        return None

    def search_by_text(node: dict, keywords: List[str], require_interactive: bool = True) -> Optional[dict]:
        """Search for element containing any of the keywords in text"""
        def condition(n):
            text = (n.get('text', '') or '').lower()
            has_index = n.get('interactive_index') is not None
            for kw in keywords:
                if kw.lower() in text:
                    if not require_interactive or has_index:
                        return True
            return False
        return search_recursive(node, condition)

    def search_by_class(node: dict, class_keywords: List[str]) -> Optional[dict]:
        """Search for element with class containing any keyword"""
        def condition(n):
            cls = (n.get('class', '') or '').lower()
            has_index = n.get('interactive_index') is not None
            for kw in class_keywords:
                if kw.lower() in cls and has_index:
                    return True
            return False
        return search_recursive(node, condition)

    def search_by_placeholder(node: dict, keywords: List[str]) -> Optional[dict]:
        """Search input by placeholder text"""
        def condition(n):
            placeholder = (n.get('placeholder', '') or '').lower()
            has_index = n.get('interactive_index') is not None
            for kw in keywords:
                if kw.lower() in placeholder and has_index:
                    return True
            return False
        return search_recursive(node, condition)

    def search_by_aria_label(node: dict, keywords: List[str]) -> Optional[dict]:
        """Search by aria-label attribute"""
        def condition(n):
            aria = (n.get('aria-label', '') or '').lower()
            has_index = n.get('interactive_index') is not None
            for kw in keywords:
                if kw.lower() in aria and has_index:
                    return True
            return False
        return search_recursive(node, condition)

    # TODO: Implement your search logic here based on task.json
    # Example searches (uncomment and modify as needed):
    #
    # element = search_by_text(dom_dict, ["New mail", "新邮件"])
    # element = search_by_class(dom_dict, ["EditorClass"])
    # element = search_by_placeholder(dom_dict, ["Subject", "主题"])
    # element = search_by_aria_label(dom_dict, ["New message"])

    element = None  # Replace with actual search

    # Return result
    if not element:
        return {"success": False, "error": "Target element not found in DOM"}

    if element.get('interactive_index') is None:
        return {"success": False, "error": "Found element but it has no interactive_index (not clickable)"}

    return {
        "success": True,
        "interactive_index": element.get("interactive_index"),
        "element_info": {
            "tag": element.get("tag"),
            "text": (element.get("text") or "")[:100],
            "xpath": element.get("xpath"),
            "class": element.get("class")
        }
    }

if __name__ == "__main__":
    # Test locally
    with open("dom_data.json", "r", encoding="utf-8") as f:
        dom = json.load(f)
    result = find_target_element(dom)
    print(json.dumps(result, indent=2, ensure_ascii=False))
'''


# =============================================================================
# Claude Agent Prompts
# =============================================================================

BROWSER_AGENT_PROMPT = """# Browser Element Finder Task

## Your Working Directory
You are working in: `{working_dir}`

## Available Files
- `task.json` - Task description with xpath hints
- `dom_data.json` - Current page DOM structure (nested JSON)
- `find_element_template.py` - Template with helper functions (copy and modify)
- `test_operation.py` - Test script to validate your find_element.py

## Your Task
Create `find_element.py` that finds the target element described in task.json.

## Instructions

### Step 1: Read task.json
```bash
cat task.json
```
Understand what element to find and the xpath hints provided.

### Step 2: Explore DOM
Search dom_data.json to find the target element:
```bash
# Search by text
grep -i "new mail" dom_data.json | head -20

# Search by class
grep -i "editorclass" dom_data.json | head -20

# Search by aria-label
grep -i "aria-label" dom_data.json | head -20
```

### Step 3: Create find_element.py
Copy the template and implement the search logic:
```bash
cp find_element_template.py find_element.py
```
Then edit find_element.py to implement the actual search.

### Step 4: Test
Run the test script to verify your implementation:
```bash
python test_operation.py
```
If it fails, read the error and fix find_element.py.

## DOM Element Structure
Each element in dom_data.json contains:
- `tag`: HTML tag (button, input, div, etc.)
- `text`: Text content
- `xpath`: XPath location
- `interactive_index`: **REQUIRED** - Index for click/fill operations
- `class`, `id`, `placeholder`, `aria-label`: HTML attributes
- `children`: Child elements

## CRITICAL Rules
1. Only elements with `interactive_index` can be clicked or filled
2. For input fields: prefer `div` with `EditorClass` over hidden `input`
3. Handle multi-language: "新邮件" = "New mail", "添加主题" = "Add subject"
4. Return `interactive_index` as an integer

## XPath Quote Normalization

**IMPORTANT**: xpath_hints may use single quotes (`'`), but dom_data.json uses double quotes (`"`).

When matching xpath, always normalize quotes:
```python
def normalize_xpath(xpath: str) -> str:
    return xpath.replace("'", '"')

# When comparing:
if normalize_xpath(node.get('xpath', '')) == normalize_xpath(target_xpath):
    return node
```

## Success Criteria
`python test_operation.py` must print "SUCCESS" and exit with code 0.
"""


SCRAPER_AGENT_PROMPT = """# Web Scraping Script Generation Task

## Working Directory

You are working in: `{working_dir}`

**Input files:**
- `requirement.json` - What data to extract
- `dom_data.json` - Webpage DOM structure (nested JSON)

**Your task:**
Create `extraction_script.py` that extracts data according to requirements.

## Instructions

1. **Read the files** to understand requirements and DOM structure
2. **Explore the DOM** using Grep/Read to find target elements
3. **Write extraction script** that returns `List[Dict[str, Any]]`

## Dual Anchor Strategy (CRITICAL)
You MUST use a "Dual Anchor" strategy for robust extraction:

1.  **Anchor 1: XPath Hints (Ground Truth Verification)**
    *   Use the provided `xpath_hints` in `requirement.json` to locate the *exact* sample element in the DOM.
    *   Verify that this element matches the data type you need.
    *   Use this to understand the *structure* of the data (e.g., "Oh, the price is in a span with class 'price'").

2.  **Anchor 2: Semantic Description (Navigation Logic)**
    *   Use the `user_description` to identify the *parent container* or *section header* that semantically bounds the data.
    *   **DO NOT** rely solely on absolute XPaths (e.g., `div[2]/div[4]`) to find the container, as these break easily.
    *   **INSTEAD**, write code that:
        a.  Finds the Semantic Anchor first (e.g., `find_element_by_text('Reputation Skyrockets')`).
        b.  Navigates to the parent container relative to that anchor.
        c.  Extracts items *within* that container using the structure learned from Anchor 1.

## Critical DOM Understanding
1.  **Text Nodes**: Text is often split across multiple child nodes (e.g., `<span>$</span><span>99</span>`). You MUST use a helper to join all text within an element.
    *   *Bad*: `element.text` (might miss children)
    *   *Good*: `"".join(element.itertext())` or similar logic.
2.  **Fragmented DOM**: Modern frameworks (React/Vue) often create deep, nested `div` structures. Do not rely on exact depth (e.g., `div/div/div`). Use relative searches (descendants) or class-based lookups where possible, *scoped* to your Semantic Anchor.

## Requirements
1.  **Read `requirement.json`**: Understand what fields to extract and the `user_description`.
2.  **Explore `dom_data.json`**: Analyze the DOM structure to find the best selectors that match the Dual Anchor strategy.
3.  **Write `extraction_script.py`**:
    *   Must be a standalone Python script.
    *   Must implement `extract_data_from_page(serialized_dom, dom_dict) -> List[Dict]`.
    *   Must handle missing fields gracefully (return `None` or empty string).
    *   **MUST** implement the "Find Header -> Find Container -> Extract" logic if a semantic anchor is described.

**Make it generic:**
- Work on similar pages with different content
- Use structural patterns (classes, tags), not hardcoded values
- Handle missing elements gracefully

## Data Requirements

**User Description:** {user_description}

**Fields to extract:**
{fields_description}{sample_description}{xpath_hints_description}

## Important Notes

- **sample_data is just ONE example** - script must work for other pages with different content
- **xpath_hints are reference only** - use them to understand structure, then adapt to actual DOM
- **Text may be split** across child nodes - combine when needed
- **Avoid hardcoding** - no magic numbers, specific text values, or assumptions from sample
- **Preserve DOM order** - DO NOT sort results. DOM order is meaningful (rankings, chronological, relevance)
- **URL fields MUST be complete URLs** - If field name contains "url" or "link" and you extract from `href` attribute:
  - Check if it's a relative path (starts with `/` but no `http://` or `https://`)
  - If relative, prepend the base URL to make it absolute
  - The base URL can be inferred from xpath_hints or user_description context
  - Example: `/leaderboard/daily` from producthunt.com → `https://www.producthunt.com/leaderboard/daily`

## XPath Quote Normalization

**IMPORTANT**: xpath_hints may use single quotes (`'`), but dom_data.json uses double quotes (`"`).

When matching xpath, always normalize quotes:
```python
def normalize_xpath(xpath: str) -> str:
    return xpath.replace("'", '"')

# When comparing:
if normalize_xpath(node.get('xpath', '')) == normalize_xpath(target_xpath):
    return node
```

## Testing

Create and run a test to validate your extraction_script.py works correctly.
"""
