"""Script Templates for Claude Agent SDK

These templates are used by Claude Agent to generate scripts.
They provide structure and helper functions that Claude fills in.
"""

# =============================================================================
# Browser Script Templates
# =============================================================================

BROWSER_TEST_OPERATION = '''#!/usr/bin/env python3
"""Test script - Validates that find_element.py correctly finds the target element.

This script:
1. Loads DOM data from dom_data.json
2. Calls find_target_element() from find_element.py
3. Validates the returned interactive_index exists in selector_map
4. Reports success or failure with details

Usage: python test_operation.py
Exit code: 0 = success, 1 = failure
"""
import json
import sys

def test():
    """Test find_element.py and validate result"""
    # Load DOM
    try:
        with open("dom_data.json", "r", encoding="utf-8") as f:
            dom_dict = json.load(f)
    except Exception as e:
        print(f"FAILED: Cannot load dom_data.json: {e}")
        return False

    # Load task info
    try:
        with open("task.json", "r", encoding="utf-8") as f:
            task_info = json.load(f)
    except Exception as e:
        print(f"FAILED: Cannot load task.json: {e}")
        return False

    # Import and run find_element
    try:
        from find_element import find_target_element
    except ImportError as e:
        print(f"FAILED: Cannot import find_element.py: {e}")
        return False
    except SyntaxError as e:
        print(f"FAILED: Syntax error in find_element.py: {e}")
        return False

    # Execute find_target_element
    try:
        result = find_target_element(dom_dict)
    except Exception as e:
        print(f"FAILED: find_target_element() raised exception: {e}")
        import traceback
        traceback.print_exc()
        return False

    # Validate result structure
    if not isinstance(result, dict):
        print(f"FAILED: find_target_element() must return dict, got {type(result)}")
        return False

    if not result.get("success"):
        error = result.get("error", "Unknown error")
        print(f"FAILED: find_target_element() returned failure: {error}")
        return False

    # Validate interactive_index
    interactive_index = result.get("interactive_index")
    if interactive_index is None:
        print("FAILED: Result missing 'interactive_index'")
        return False

    if not isinstance(interactive_index, int):
        print(f"FAILED: interactive_index must be int, got {type(interactive_index)}")
        return False

    # Validate element_info
    element_info = result.get("element_info", {})
    if not element_info:
        print("WARNING: Result missing 'element_info', but interactive_index is valid")

    # Success!
    print(f"SUCCESS: Found element")
    print(f"  interactive_index: {interactive_index}")
    print(f"  tag: {element_info.get('tag', 'N/A')}")
    print(f"  text: {element_info.get('text', 'N/A')[:50] if element_info.get('text') else 'N/A'}")
    print(f"  class: {element_info.get('class', 'N/A')[:50] if element_info.get('class') else 'N/A'}")
    return True

if __name__ == "__main__":
    success = test()
    sys.exit(0 if success else 1)
'''


BROWSER_FIND_ELEMENT_TEMPLATE = '''#!/usr/bin/env python3
"""Find target element in DOM - Generated by Claude Agent

This script finds the target element based on task description and xpath hints.
It searches dom_data.json and returns the interactive_index of the target element.

IMPORTANT:
- Only elements with 'interactive_index' can be clicked or filled
- For input fields, prefer div with 'EditorClass' over hidden inputs
- Handle both Chinese and English text (e.g., "新邮件" = "New mail")
"""
import json
from typing import Dict, Optional, List

def find_target_element(dom_dict: dict) -> dict:
    """Find target element and return its interactive_index

    Args:
        dom_dict: DOM dictionary loaded from dom_data.json

    Returns:
        dict with:
        - success: bool
        - interactive_index: int (element index for click/fill operations)
        - element_info: dict with tag, text, xpath, class (for debugging)
        - error: str (if success is False)
    """

    def search_recursive(node: dict, condition_fn) -> Optional[dict]:
        """Recursively search DOM tree with a condition function"""
        if condition_fn(node):
            return node
        for child in node.get('children', []):
            result = search_recursive(child, condition_fn)
            if result:
                return result
        return None

    def search_by_text(node: dict, keywords: List[str], require_interactive: bool = True) -> Optional[dict]:
        """Search for element containing any of the keywords in text"""
        def condition(n):
            text = (n.get('text', '') or '').lower()
            has_index = n.get('interactive_index') is not None
            for kw in keywords:
                if kw.lower() in text:
                    if not require_interactive or has_index:
                        return True
            return False
        return search_recursive(node, condition)

    def search_by_class(node: dict, class_keywords: List[str]) -> Optional[dict]:
        """Search for element with class containing any keyword"""
        def condition(n):
            cls = (n.get('class', '') or '').lower()
            has_index = n.get('interactive_index') is not None
            for kw in class_keywords:
                if kw.lower() in cls and has_index:
                    return True
            return False
        return search_recursive(node, condition)

    def search_by_placeholder(node: dict, keywords: List[str]) -> Optional[dict]:
        """Search input by placeholder text"""
        def condition(n):
            placeholder = (n.get('placeholder', '') or '').lower()
            has_index = n.get('interactive_index') is not None
            for kw in keywords:
                if kw.lower() in placeholder and has_index:
                    return True
            return False
        return search_recursive(node, condition)

    def search_by_aria_label(node: dict, keywords: List[str]) -> Optional[dict]:
        """Search by aria-label attribute"""
        def condition(n):
            aria = (n.get('aria-label', '') or '').lower()
            has_index = n.get('interactive_index') is not None
            for kw in keywords:
                if kw.lower() in aria and has_index:
                    return True
            return False
        return search_recursive(node, condition)

    # TODO: Implement your search logic here based on task.json
    # Example searches (uncomment and modify as needed):
    #
    # element = search_by_text(dom_dict, ["New mail", "新邮件"])
    # element = search_by_class(dom_dict, ["EditorClass"])
    # element = search_by_placeholder(dom_dict, ["Subject", "主题"])
    # element = search_by_aria_label(dom_dict, ["New message"])

    element = None  # Replace with actual search

    # Return result
    if not element:
        return {"success": False, "error": "Target element not found in DOM"}

    if element.get('interactive_index') is None:
        return {"success": False, "error": "Found element but it has no interactive_index (not clickable)"}

    return {
        "success": True,
        "interactive_index": element.get("interactive_index"),
        "element_info": {
            "tag": element.get("tag"),
            "text": (element.get("text") or "")[:100],
            "xpath": element.get("xpath"),
            "class": element.get("class")
        }
    }

if __name__ == "__main__":
    # Test locally
    with open("dom_data.json", "r", encoding="utf-8") as f:
        dom = json.load(f)
    result = find_target_element(dom)
    print(json.dumps(result, indent=2, ensure_ascii=False))
'''


# =============================================================================
# Claude Agent Prompts
# =============================================================================

BROWSER_AGENT_PROMPT = """# Browser Element Finder Task

## Your Working Directory
You are working in: `{working_dir}`

## Available Files
- `task.json` - Task description with xpath hints
- `dom_data.json` - Current page DOM structure (nested JSON)
- `find_element_template.py` - Template with helper functions (copy and modify)
- `test_operation.py` - Test script to validate your find_element.py

## Your Task
Create `find_element.py` that finds the target element described in task.json.

## Available Skills

**IMPORTANT**: Read the skill SKILL.md file first for detailed guidance:
```bash
cat .claude/skills/element-finder/SKILL.md
```

**Element Tools** - Use these to find elements BEFORE writing script:
```bash
# Analyze xpath hint from recording (RECOMMENDED FIRST STEP)
python .claude/skills/element-finder/tools/element_tools.py hint "<xpath_from_task.json>"

# Search by text keyword (searches text, aria-label, placeholder)
python .claude/skills/element-finder/tools/element_tools.py search "Submit"

# Find element by xpath, check if it has interactive_index
python .claude/skills/element-finder/tools/element_tools.py find "<xpath>"

# List all interactive elements in a container
python .claude/skills/element-finder/tools/element_tools.py list "<container_xpath>"

# Search by specific attribute
python .claude/skills/element-finder/tools/element_tools.py attr "aria-label" "Send message"
```

## Instructions

### Step 1: Read task.json
```bash
cat task.json
```
Understand what element to find and the xpath hints provided.

### Step 2: Use Element Tools
Use the element tools to find the target element:
```bash
# First, try the hint command with xpath from task.json
python .claude/skills/element-finder/tools/element_tools.py hint "<xpath_hint>"

# If hint fails, search by text keywords
python .claude/skills/element-finder/tools/element_tools.py search "<keyword>"
```

### Step 3: Create find_element.py
Copy the template and implement the search logic based on what tools found:
```bash
cp find_element_template.py find_element.py
```
Then edit find_element.py to implement the actual search.

### Step 4: Test
Run the test script to verify your implementation:
```bash
python test_operation.py
```
If it fails, read the error and fix find_element.py.

## DOM Element Structure
Each element in dom_data.json contains:
- `tag`: HTML tag (button, input, div, etc.)
- `text`: Text content
- `xpath`: XPath location
- `interactive_index`: **REQUIRED** - Index for click/fill operations
- `class`, `id`, `placeholder`, `aria-label`: HTML attributes
- `children`: Child elements

## CRITICAL Rules
1. Only elements with `interactive_index` can be clicked or filled
2. For input fields: prefer `div` with `EditorClass` over hidden `input`
3. Handle multi-language: "新邮件" = "New mail", "添加主题" = "Add subject"
4. Return `interactive_index` as an integer

## XPath Quote Normalization

**IMPORTANT**: xpath_hints may use single quotes (`'`), but dom_data.json uses double quotes (`"`).

When matching xpath, always normalize quotes:
```python
def normalize_xpath(xpath: str) -> str:
    return xpath.replace("'", '"')

# When comparing:
if normalize_xpath(node.get('xpath', '')) == normalize_xpath(target_xpath):
    return node
```

## Success Criteria
`python test_operation.py` must print "SUCCESS" and exit with code 0.
"""


SCRAPER_AGENT_PROMPT = """# Data Extraction Script Generation

Generate `extraction_script.py` to extract data from the webpage DOM.

## Task Context

- **Working Directory**: `{working_dir}`
- **Page URL**: `{page_url}`

## Input Files

- `requirement.json` - User requirements, output format, xpath hints
- `dom_data.json` - Page DOM as nested JSON dictionary

## DOM Tools

DOM analysis tools are available at `.claude/skills/dom-extraction/tools/dom_tools.py`.

**IMPORTANT**: Read `.claude/skills/dom-extraction/SKILL.md` first for supported commands, syntax, and detailed workflow. Do not guess parameters.

## Workflow

1. Read `requirement.json` to understand what to extract
2. Use `find` with the xpath_hint to locate the element
3. Remove index suffix `[1]` to get container xpath, then use `analyze`
4. Write `extraction_script.py` with function `extract_data_from_page(dom_dict) -> List[Dict]`
5. Test: `python extraction_script.py`

## CRITICAL: URLs Must Be Absolute

All URLs in extracted data MUST be absolute. Use `urljoin("{page_url}", relative_url)` to convert.
Relative URLs like `/products/xxx` will cause navigation failures!
"""
