"""
Workflow Validation Tool (v2 Format Support)

Provides rule-based validation for generated workflows.
This is used by Claude Agent as a tool to check workflow correctness.

Validation rules are aligned with BaseApp's workflow_loader.py to ensure
workflows generated by Cloud Backend can be executed by BaseApp.

Supports both v1 and v2 workflow formats.
"""

import re
import yaml
from typing import Dict, List, Any, Set, Tuple
from dataclasses import dataclass, field
import logging

logger = logging.getLogger(__name__)

# Valid agent types (must match BaseApp's AGENT_TYPES)
VALID_AGENT_TYPES = {
    "browser_agent",
    "scraper_agent",
    "storage_agent",
    "variable",
    "text_agent",
    "autonomous_browser_agent",
}

# Control flow keys (v2 syntax)
CONTROL_FLOW_KEYS = {"foreach", "if", "while"}

# Agent-specific required fields
# Format: { agent_type: { "step": [...], "inputs": [...] } }
AGENT_SPECIFIC_FIELDS = {
    "text_agent": {"step": [], "inputs": ["instruction"]},
    "variable": {"step": [], "inputs": []},
    "scraper_agent": {"step": [], "inputs": []},
    "browser_agent": {"step": [], "inputs": []},
    "storage_agent": {"step": [], "inputs": []},
}


@dataclass
class ValidationResult:
    """Result of workflow validation"""
    valid: bool
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "valid": self.valid,
            "errors": self.errors,
            "warnings": self.warnings
        }

    def to_string(self) -> str:
        """Convert to human-readable string for Claude Agent"""
        if self.valid and not self.warnings:
            return "VALIDATION PASSED"

        parts = []
        if not self.valid:
            parts.append("VALIDATION FAILED")
            parts.append(f"Errors ({len(self.errors)}):")
            for i, error in enumerate(self.errors, 1):
                parts.append(f"  {i}. {error}")

        if self.warnings:
            parts.append(f"Warnings ({len(self.warnings)}):")
            for i, warning in enumerate(self.warnings, 1):
                parts.append(f"  {i}. {warning}")

        if self.valid:
            parts.insert(0, "VALIDATION PASSED (with warnings)")

        return "\n".join(parts)


class RuleValidator:
    """Rule-based workflow validator supporting v1 and v2 formats"""

    def validate(self, workflow: Dict[str, Any]) -> ValidationResult:
        """
        Validate a workflow dictionary.

        Args:
            workflow: Parsed workflow dictionary

        Returns:
            ValidationResult with errors and warnings
        """
        errors = []
        warnings = []

        # Detect format version
        is_v2 = self._is_v2_format(workflow)

        # 1. Check required root fields
        errors.extend(self._check_required_fields(workflow, is_v2))

        # 2. Check agent types
        errors.extend(self._check_agent_types(workflow))

        # 3. Check variable references
        var_errors, var_warnings = self._check_variables(workflow, is_v2)
        errors.extend(var_errors)
        warnings.extend(var_warnings)

        # 4. Check control flow structures
        errors.extend(self._check_control_flow_structure(workflow))

        # 5. Check agent-specific required fields
        errors.extend(self._check_agent_specific_fields(workflow))

        # 6. Check step IDs are unique
        errors.extend(self._check_unique_step_ids(workflow))

        return ValidationResult(
            valid=len(errors) == 0,
            errors=errors,
            warnings=warnings
        )

    def _is_v2_format(self, workflow: Dict) -> bool:
        """Detect if workflow uses v2 format"""
        if "name" in workflow and "metadata" not in workflow:
            return True
        api_version = workflow.get("apiVersion", "")
        if "v2" in api_version:
            return True
        return False

    def _check_required_fields(self, workflow: Dict, is_v2: bool) -> List[str]:
        """Check required root fields"""
        errors = []

        # apiVersion is always required
        if "apiVersion" not in workflow:
            errors.append("Missing required field: 'apiVersion'")
        else:
            api_version = workflow["apiVersion"]
            if not api_version.startswith("ami.io/v"):
                errors.append(f"Invalid apiVersion '{api_version}'. Must start with 'ami.io/v'")

        # steps is always required
        if "steps" not in workflow:
            errors.append("Missing required field: 'steps'")

        if is_v2:
            # v2: name at root level
            if "name" not in workflow:
                errors.append("Missing required field: 'name'")
        else:
            # v1: kind and metadata required
            if "kind" not in workflow:
                errors.append("Missing required field: 'kind'")
            if "metadata" not in workflow:
                errors.append("Missing required field: 'metadata'")
            elif isinstance(workflow.get("metadata"), dict):
                if "name" not in workflow["metadata"]:
                    errors.append("Missing required field: 'metadata.name'")

        return errors

    def _check_agent_types(self, workflow: Dict) -> List[str]:
        """Check agent types are valid"""
        errors = []
        steps = workflow.get("steps", [])

        def check_steps(steps: List[Dict], path: str = "steps"):
            for i, step in enumerate(steps):
                step_path = f"{path}[{i}]"
                step_id = step.get("id", f"index_{i}")

                # Check if it's v2 control flow syntax
                is_control_flow = any(key in step for key in CONTROL_FLOW_KEYS)

                if is_control_flow:
                    # v2 control flow - validate nested steps
                    if "foreach" in step:
                        sub_steps = step.get("do") or step.get("steps", [])
                        check_steps(sub_steps, f"{step_path}.do")
                    elif "if" in step:
                        if "then" in step:
                            check_steps(step["then"], f"{step_path}.then")
                        if "else" in step:
                            check_steps(step["else"], f"{step_path}.else")
                    elif "while" in step:
                        sub_steps = step.get("do") or step.get("steps", [])
                        check_steps(sub_steps, f"{step_path}.do")
                else:
                    # Agent step - check agent type
                    agent_type = step.get("agent") or step.get("agent_type")

                    if agent_type is None:
                        errors.append(f"Step '{step_id}' at {step_path} missing 'agent' field")
                    elif agent_type not in VALID_AGENT_TYPES:
                        errors.append(
                            f"Invalid agent '{agent_type}' at step '{step_id}'. "
                            f"Valid types: {', '.join(sorted(VALID_AGENT_TYPES))}"
                        )

                    # Check nested steps for v1 control flow
                    if agent_type == "foreach" and "steps" in step:
                        check_steps(step["steps"], f"{step_path}.steps")
                    if "then_steps" in step:
                        check_steps(step["then_steps"], f"{step_path}.then_steps")
                    if "else_steps" in step:
                        check_steps(step["else_steps"], f"{step_path}.else_steps")

        check_steps(steps)
        return errors

    def _check_variables(self, workflow: Dict, is_v2: bool) -> Tuple[List[str], List[str]]:
        """Check variable references have definitions"""
        errors = []
        warnings = []
        defined_vars: Set[str] = set()

        # Collect input variables
        if is_v2:
            if "input" in workflow:
                input_name = workflow["input"]
                if isinstance(input_name, str):
                    defined_vars.add(input_name)
            if "inputs" in workflow:
                for var_name in workflow["inputs"].keys():
                    defined_vars.add(var_name)
        else:
            for var_name in workflow.get("inputs", {}).keys():
                defined_vars.add(var_name)

        steps = workflow.get("steps", [])
        self._check_steps_variables(steps, defined_vars, errors, warnings, set())

        return errors, warnings

    def _check_steps_variables(
        self,
        steps: List[Dict],
        defined_vars: Set[str],
        errors: List[str],
        warnings: List[str],
        loop_vars: Set[str]
    ):
        """Recursively check variables in steps"""
        for step in steps:
            step_id = step.get("id", "unknown")

            # Check if it's v2 control flow
            is_foreach = "foreach" in step
            is_if = "if" in step
            is_while = "while" in step

            if is_foreach:
                source = step["foreach"]
                item_var = step.get("as", "item")
                index_var = step.get("index_var", "index")

                self._check_var_references(
                    {"source": source},
                    defined_vars | loop_vars,
                    errors,
                    f"foreach source"
                )

                new_loop_vars = loop_vars | {item_var, index_var}
                sub_steps = step.get("do") or step.get("steps", [])
                self._check_steps_variables(
                    sub_steps,
                    defined_vars.copy(),
                    errors,
                    warnings,
                    new_loop_vars
                )

            elif is_if:
                condition = step["if"]
                self._check_var_references(
                    condition,
                    defined_vars | loop_vars,
                    errors,
                    f"if condition"
                )

                if "then" in step:
                    self._check_steps_variables(
                        step["then"],
                        defined_vars.copy(),
                        errors,
                        warnings,
                        loop_vars
                    )
                if "else" in step:
                    self._check_steps_variables(
                        step["else"],
                        defined_vars.copy(),
                        errors,
                        warnings,
                        loop_vars
                    )

            elif is_while:
                condition = step["while"]
                self._check_var_references(
                    condition,
                    defined_vars | loop_vars,
                    errors,
                    f"while condition"
                )

                sub_steps = step.get("do") or step.get("steps", [])
                self._check_steps_variables(
                    sub_steps,
                    defined_vars.copy(),
                    errors,
                    warnings,
                    loop_vars
                )

            else:
                # Agent step
                agent_type = step.get("agent") or step.get("agent_type")

                self._check_var_references(
                    step.get("inputs", {}),
                    defined_vars | loop_vars,
                    errors,
                    f"step '{step_id}' inputs"
                )

                if "condition" in step:
                    self._check_var_references(
                        step["condition"],
                        defined_vars | loop_vars,
                        errors,
                        f"step '{step_id}' condition"
                    )

                # Add outputs to defined vars
                for var_name in step.get("outputs", {}).values():
                    if isinstance(var_name, str):
                        defined_vars.add(var_name)

                # v1 control flow (agent_type: foreach)
                if agent_type == "foreach":
                    item_var = step.get("item_var", "item")
                    index_var = step.get("index_var", "index")
                    source = step.get("source", "")

                    self._check_var_references(
                        {"source": source},
                        defined_vars | loop_vars,
                        errors,
                        f"step '{step_id}' foreach source"
                    )

                    new_loop_vars = loop_vars | {item_var, index_var}
                    if "steps" in step:
                        self._check_steps_variables(
                            step["steps"],
                            defined_vars.copy(),
                            errors,
                            warnings,
                            new_loop_vars
                        )

                if "then_steps" in step:
                    self._check_steps_variables(
                        step["then_steps"],
                        defined_vars.copy(),
                        errors,
                        warnings,
                        loop_vars
                    )
                if "else_steps" in step:
                    self._check_steps_variables(
                        step["else_steps"],
                        defined_vars.copy(),
                        errors,
                        warnings,
                        loop_vars
                    )

    def _check_var_references(
        self,
        obj: Any,
        defined_vars: Set[str],
        errors: List[str],
        context: str
    ):
        """Check variable references in an object"""
        if isinstance(obj, str):
            refs = re.findall(r'\{\{(\w+)(?:[\.\[\]\w]*)*\}\}', obj)
            for var_name in refs:
                if var_name not in defined_vars:
                    errors.append(
                        f"Undefined variable '{{{{{var_name}}}}}' referenced in {context}"
                    )
        elif isinstance(obj, dict):
            for value in obj.values():
                self._check_var_references(value, defined_vars, errors, context)
        elif isinstance(obj, list):
            for item in obj:
                self._check_var_references(item, defined_vars, errors, context)

    def _check_control_flow_structure(self, workflow: Dict) -> List[str]:
        """Check control flow structures have required fields"""
        errors = []
        steps = workflow.get("steps", [])

        def check_steps(steps: List[Dict], path: str = "steps"):
            for i, step in enumerate(steps):
                step_path = f"{path}[{i}]"
                step_id = step.get("id", f"index_{i}")

                # v2 control flow syntax
                if "foreach" in step:
                    sub_steps = step.get("do") or step.get("steps")
                    if not sub_steps:
                        errors.append(
                            f"foreach at {step_path} missing 'do' or 'steps' field"
                        )
                    else:
                        check_steps(sub_steps, f"{step_path}.do")

                elif "if" in step:
                    if "then" not in step:
                        errors.append(
                            f"if at {step_path} missing required 'then' field"
                        )
                    else:
                        check_steps(step["then"], f"{step_path}.then")
                    if "else" in step:
                        check_steps(step["else"], f"{step_path}.else")

                elif "while" in step:
                    sub_steps = step.get("do") or step.get("steps")
                    if not sub_steps:
                        errors.append(
                            f"while at {step_path} missing 'do' or 'steps' field"
                        )
                    else:
                        check_steps(sub_steps, f"{step_path}.do")

                else:
                    # v1 control flow
                    agent_type = step.get("agent") or step.get("agent_type")

                    if agent_type == "foreach":
                        if "source" not in step:
                            errors.append(
                                f"foreach step '{step_id}' at {step_path} missing 'source' field"
                            )
                        if "steps" not in step:
                            errors.append(
                                f"foreach step '{step_id}' at {step_path} missing 'steps' field"
                            )
                        else:
                            check_steps(step["steps"], f"{step_path}.steps")

                    elif agent_type == "if":
                        if "condition" not in step:
                            errors.append(
                                f"if step '{step_id}' at {step_path} missing 'condition' field"
                            )
                        if "then" not in step and "then_steps" not in step:
                            errors.append(
                                f"if step '{step_id}' at {step_path} missing 'then' field"
                            )
                        if "then" in step:
                            check_steps(step["then"], f"{step_path}.then")
                        if "then_steps" in step:
                            check_steps(step["then_steps"], f"{step_path}.then_steps")
                        if "else" in step:
                            check_steps(step["else"], f"{step_path}.else")
                        if "else_steps" in step:
                            check_steps(step["else_steps"], f"{step_path}.else_steps")

                    elif agent_type == "while":
                        if "condition" not in step:
                            errors.append(
                                f"while step '{step_id}' at {step_path} missing 'condition' field"
                            )
                        if "steps" not in step:
                            errors.append(
                                f"while step '{step_id}' at {step_path} missing 'steps' field"
                            )
                        else:
                            check_steps(step["steps"], f"{step_path}.steps")

        check_steps(steps)
        return errors

    def _check_agent_specific_fields(self, workflow: Dict) -> List[str]:
        """Check agent-specific required fields"""
        errors = []
        steps = workflow.get("steps", [])

        def check_steps(steps: List[Dict], path: str = "steps"):
            for i, step in enumerate(steps):
                step_path = f"{path}[{i}]"
                step_id = step.get("id", f"index_{i}")

                # Skip v2 control flow
                if any(key in step for key in CONTROL_FLOW_KEYS):
                    if "foreach" in step:
                        sub_steps = step.get("do") or step.get("steps", [])
                        check_steps(sub_steps, f"{step_path}.do")
                    elif "if" in step:
                        if "then" in step:
                            check_steps(step["then"], f"{step_path}.then")
                        if "else" in step:
                            check_steps(step["else"], f"{step_path}.else")
                    elif "while" in step:
                        sub_steps = step.get("do") or step.get("steps", [])
                        check_steps(sub_steps, f"{step_path}.do")
                    continue

                agent_type = step.get("agent") or step.get("agent_type")

                if agent_type in AGENT_SPECIFIC_FIELDS:
                    field_config = AGENT_SPECIFIC_FIELDS[agent_type]

                    for f in field_config.get("step", []):
                        if f not in step:
                            errors.append(
                                f"Step '{step_id}' ({agent_type}) at {step_path} missing required '{f}' field"
                            )

                    step_inputs = step.get("inputs", {})
                    for f in field_config.get("inputs", []):
                        if f not in step_inputs:
                            errors.append(
                                f"Step '{step_id}' ({agent_type}) at {step_path} missing required 'inputs.{f}' field"
                            )

                if "steps" in step:
                    check_steps(step["steps"], f"{step_path}.steps")
                if "then" in step:
                    check_steps(step["then"], f"{step_path}.then")
                if "then_steps" in step:
                    check_steps(step["then_steps"], f"{step_path}.then_steps")
                if "else" in step:
                    check_steps(step["else"], f"{step_path}.else")
                if "else_steps" in step:
                    check_steps(step["else_steps"], f"{step_path}.else_steps")

        check_steps(steps)
        return errors

    def _check_unique_step_ids(self, workflow: Dict) -> List[str]:
        """Check all step IDs are unique"""
        errors = []
        seen_ids: Set[str] = set()
        steps = workflow.get("steps", [])

        def collect_ids(steps: List[Dict], path: str = "steps"):
            for i, step in enumerate(steps):
                step_id = step.get("id")
                step_path = f"{path}[{i}]"

                if step_id:
                    if step_id in seen_ids:
                        errors.append(f"Duplicate step id '{step_id}' at {step_path}")
                    else:
                        seen_ids.add(step_id)

                for key in ["steps", "do", "then", "else", "then_steps", "else_steps"]:
                    if key in step and isinstance(step[key], list):
                        collect_ids(step[key], f"{step_path}.{key}")

        collect_ids(steps)
        return errors


# Singleton validator instance
_validator = RuleValidator()


def validate_workflow_yaml(yaml_content: str) -> str:
    """
    Validate workflow YAML content.

    This is the main entry point for Claude Agent to use as a tool.

    Args:
        yaml_content: Workflow YAML string

    Returns:
        Human-readable validation result string
    """
    try:
        workflow = yaml.safe_load(yaml_content)
    except yaml.YAMLError as e:
        return f"YAML parse error: {e}"

    if not isinstance(workflow, dict):
        return "Invalid workflow: expected a YAML dictionary/object"

    result = _validator.validate(workflow)
    return result.to_string()


def validate_workflow_dict(workflow: Dict[str, Any]) -> ValidationResult:
    """
    Validate workflow dictionary (for programmatic use).

    Args:
        workflow: Parsed workflow dictionary

    Returns:
        ValidationResult object
    """
    if not isinstance(workflow, dict):
        return ValidationResult(
            valid=False,
            errors=[f"Invalid workflow type: expected dict, got {type(workflow).__name__}"]
        )
    return _validator.validate(workflow)
