"""
Workflow Validation Tool (v2 Format Support)

Provides rule-based validation for generated workflows.
This is used by Claude Agent as a tool to check workflow correctness.

Validation rules are aligned with BaseApp's workflow_loader.py to ensure
workflows generated by Cloud Backend can be executed by BaseApp.

Supports both v1 and v2 workflow formats.

Uses INPUT_SCHEMA from agents to validate required inputs.
"""

import re
import yaml
from typing import Dict, List, Any, Set, Tuple, Optional
from dataclasses import dataclass, field
import logging

logger = logging.getLogger(__name__)

# Valid agent types (must match BaseApp's AGENT_TYPES)
VALID_AGENT_TYPES = {
    "browser_agent",
    "scraper_agent",
    "storage_agent",
    "variable",
    "text_agent",
    "autonomous_browser_agent",
    "tavily_agent",
}

# Control flow keys (v2 syntax)
CONTROL_FLOW_KEYS = {"foreach", "if", "while"}

# Agent schemas removed (step agents deleted), use hardcoded AGENT_SPECIFIC_FIELDS fallback
AGENT_SCHEMAS = {}
AGENT_SCHEMAS_AVAILABLE = False

# Fallback: Agent-specific required fields (used when schemas not available)
# Format: { agent_type: { "step": [...], "inputs": [...] } }
AGENT_SPECIFIC_FIELDS = {
    "text_agent": {"step": [], "inputs": ["instruction"]},
    "variable": {"step": [], "inputs": ["operation", "data"]},
    "scraper_agent": {"step": [], "inputs": ["data_requirements"]},
    "browser_agent": {"step": [], "inputs": []},
    "storage_agent": {"step": [], "inputs": ["operation", "collection"]},
    "autonomous_browser_agent": {"step": [], "inputs": ["task"]},
    "tavily_agent": {"step": [], "inputs": ["operation", "query"]},
}

# Agent output types for variable scope validation
# Based on agent-specs/SKILL.md output contracts
# Types: "list" (List[Dict]), "dict" (Dict), "any" (could be scalar from LLM)
AGENT_OUTPUT_TYPES: Dict[str, str] = {
    "scraper_agent": "list",      # List[Dict] - supports .0.field, .length
    "text_agent": "any",          # LLM may return scalar in result field
    "variable": "any",            # Depends on operation
    "browser_agent": "dict",      # {url, title, success, clipboard_content?}
    "storage_agent": "dict",      # {count, ...}
    "tavily_agent": "dict",       # {query, results, answer?, images?}
    "autonomous_browser_agent": "dict",
}

# Known fields for dict-type agent outputs (for validation hints)
AGENT_KNOWN_FIELDS: Dict[str, Set[str]] = {
    "browser_agent": {"url", "title", "success", "clipboard_content", "current_tab_index", "open_tabs_count"},
    "storage_agent": {"count"},
    "tavily_agent": {"query", "results", "answer", "images"},
}


@dataclass
class VariableInfo:
    """Information about a defined variable for scope validation"""
    name: str
    var_type: str  # "list", "dict", "any", "scalar", "loop_item"
    defined_at: str  # step_id or "input" or "loop:path"
    agent_type: Optional[str] = None


@dataclass
class ValidationResult:
    """Result of workflow validation"""
    valid: bool
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "valid": self.valid,
            "errors": self.errors,
            "warnings": self.warnings
        }

    def to_string(self) -> str:
        """Convert to human-readable string for Claude Agent"""
        if self.valid and not self.warnings:
            return "VALIDATION PASSED"

        parts = []
        if not self.valid:
            parts.append("VALIDATION FAILED")
            parts.append(f"Errors ({len(self.errors)}):")
            for i, error in enumerate(self.errors, 1):
                parts.append(f"  {i}. {error}")

        if self.warnings:
            parts.append(f"Warnings ({len(self.warnings)}):")
            for i, warning in enumerate(self.warnings, 1):
                parts.append(f"  {i}. {warning}")

        if self.valid:
            parts.insert(0, "VALIDATION PASSED (with warnings)")

        return "\n".join(parts)


class RuleValidator:
    """Rule-based workflow validator supporting v1 and v2 formats"""

    def validate(self, workflow: Dict[str, Any]) -> ValidationResult:
        """
        Validate a workflow dictionary.

        Args:
            workflow: Parsed workflow dictionary

        Returns:
            ValidationResult with errors and warnings
        """
        errors = []
        warnings = []

        # Detect format version
        is_v2 = self._is_v2_format(workflow)

        # 1. Check required root fields
        errors.extend(self._check_required_fields(workflow, is_v2))

        # 2. Check agent types
        errors.extend(self._check_agent_types(workflow))

        # 3. Check variable references
        var_errors, var_warnings = self._check_variables(workflow, is_v2)
        errors.extend(var_errors)
        warnings.extend(var_warnings)

        # 4. Check control flow structures
        errors.extend(self._check_control_flow_structure(workflow))

        # 5. Check agent-specific required fields
        errors.extend(self._check_agent_specific_fields(workflow))

        # 6. Check step IDs are unique
        errors.extend(self._check_unique_step_ids(workflow))

        return ValidationResult(
            valid=len(errors) == 0,
            errors=errors,
            warnings=warnings
        )

    def _is_v2_format(self, workflow: Dict) -> bool:
        """Detect if workflow uses v2 format"""
        if "name" in workflow and "metadata" not in workflow:
            return True
        api_version = workflow.get("apiVersion", "")
        if "v2" in api_version:
            return True
        return False

    def _check_required_fields(self, workflow: Dict, is_v2: bool) -> List[str]:
        """Check required root fields"""
        errors = []

        # apiVersion is always required
        if "apiVersion" not in workflow:
            errors.append("Missing required field: 'apiVersion'")
        else:
            api_version = workflow["apiVersion"]
            if not api_version.startswith("ami.io/v"):
                errors.append(f"Invalid apiVersion '{api_version}'. Must start with 'ami.io/v'")

        # steps is always required
        if "steps" not in workflow:
            errors.append("Missing required field: 'steps'")

        if is_v2:
            # v2: name at root level
            if "name" not in workflow:
                errors.append("Missing required field: 'name'")
        else:
            # v1: kind and metadata required
            if "kind" not in workflow:
                errors.append("Missing required field: 'kind'")
            if "metadata" not in workflow:
                errors.append("Missing required field: 'metadata'")
            elif isinstance(workflow.get("metadata"), dict):
                if "name" not in workflow["metadata"]:
                    errors.append("Missing required field: 'metadata.name'")

        return errors

    def _check_agent_types(self, workflow: Dict) -> List[str]:
        """Check agent types are valid"""
        errors = []
        steps = workflow.get("steps", [])

        def check_steps(steps: List[Dict], path: str = "steps"):
            for i, step in enumerate(steps):
                step_path = f"{path}[{i}]"
                step_id = step.get("id", f"index_{i}")

                # Check if it's v2 control flow syntax
                is_control_flow = any(key in step for key in CONTROL_FLOW_KEYS)

                if is_control_flow:
                    # v2 control flow - validate nested steps
                    if "foreach" in step:
                        sub_steps = step.get("do") or step.get("steps", [])
                        check_steps(sub_steps, f"{step_path}.do")
                    elif "if" in step:
                        if "then" in step:
                            check_steps(step["then"], f"{step_path}.then")
                        if "else" in step:
                            check_steps(step["else"], f"{step_path}.else")
                    elif "while" in step:
                        sub_steps = step.get("do") or step.get("steps", [])
                        check_steps(sub_steps, f"{step_path}.do")
                else:
                    # Agent step - check agent type
                    agent_type = step.get("agent") or step.get("agent_type")

                    if agent_type is None:
                        errors.append(f"Step '{step_id}' at {step_path} missing 'agent' field")
                    elif agent_type not in VALID_AGENT_TYPES:
                        errors.append(
                            f"Invalid agent '{agent_type}' at step '{step_id}'. "
                            f"Valid types: {', '.join(sorted(VALID_AGENT_TYPES))}"
                        )

                    # Check nested steps for v1 control flow
                    if agent_type == "foreach" and "steps" in step:
                        check_steps(step["steps"], f"{step_path}.steps")
                    if "then_steps" in step:
                        check_steps(step["then_steps"], f"{step_path}.then_steps")
                    if "else_steps" in step:
                        check_steps(step["else_steps"], f"{step_path}.else_steps")

        check_steps(steps)
        return errors

    def _check_variables(self, workflow: Dict, is_v2: bool) -> Tuple[List[str], List[str]]:
        """Check variable references, definitions, and type-based property access"""
        errors = []
        warnings = []
        # Use Dict[str, VariableInfo] instead of Set[str] for type tracking
        defined_vars: Dict[str, VariableInfo] = {}

        # Collect input variables
        if is_v2:
            if "input" in workflow:
                input_name = workflow["input"]
                if isinstance(input_name, str):
                    defined_vars[input_name] = VariableInfo(
                        name=input_name, var_type="any", defined_at="input"
                    )
            if "inputs" in workflow:
                for var_name in workflow["inputs"].keys():
                    defined_vars[var_name] = VariableInfo(
                        name=var_name, var_type="any", defined_at="input"
                    )
        else:
            for var_name in workflow.get("inputs", {}).keys():
                defined_vars[var_name] = VariableInfo(
                    name=var_name, var_type="any", defined_at="input"
                )

        steps = workflow.get("steps", [])
        loop_vars: Dict[str, VariableInfo] = {}
        self._check_steps_variables(steps, defined_vars, errors, warnings, loop_vars)

        return errors, warnings

    def _check_steps_variables(
        self,
        steps: List[Dict],
        defined_vars: Dict[str, VariableInfo],
        errors: List[str],
        warnings: List[str],
        loop_vars: Dict[str, VariableInfo]
    ):
        """Recursively check variables in steps with type tracking"""
        for step in steps:
            step_id = step.get("id", "unknown")

            # Check if it's v2 control flow
            is_foreach = "foreach" in step
            is_if = "if" in step
            is_while = "while" in step

            if is_foreach:
                source = step["foreach"]
                item_var = step.get("as", "item")
                index_var = step.get("index_var", "index")

                self._check_var_references_typed(
                    {"source": source},
                    defined_vars,
                    loop_vars,
                    errors,
                    warnings,
                    f"foreach source"
                )

                # Infer item type from source
                item_type = "loop_item"
                if isinstance(source, str):
                    source_var = self._extract_base_var(source)
                    if source_var:
                        all_vars = {**defined_vars, **loop_vars}
                        if source_var in all_vars and all_vars[source_var].var_type == "list":
                            item_type = "dict"  # List items are typically Dict

                new_loop_vars = dict(loop_vars)
                new_loop_vars[item_var] = VariableInfo(
                    name=item_var, var_type=item_type, defined_at=f"loop:{step_id}"
                )
                new_loop_vars[index_var] = VariableInfo(
                    name=index_var, var_type="scalar", defined_at=f"loop:{step_id}"
                )

                sub_steps = step.get("do") or step.get("steps", [])
                self._check_steps_variables(
                    sub_steps,
                    dict(defined_vars),
                    errors,
                    warnings,
                    new_loop_vars
                )

            elif is_if:
                condition = step["if"]
                self._check_var_references_typed(
                    condition,
                    defined_vars,
                    loop_vars,
                    errors,
                    warnings,
                    f"if condition"
                )

                if "then" in step:
                    self._check_steps_variables(
                        step["then"],
                        dict(defined_vars),
                        errors,
                        warnings,
                        loop_vars
                    )
                if "else" in step:
                    self._check_steps_variables(
                        step["else"],
                        dict(defined_vars),
                        errors,
                        warnings,
                        loop_vars
                    )

            elif is_while:
                condition = step["while"]
                self._check_var_references_typed(
                    condition,
                    defined_vars,
                    loop_vars,
                    errors,
                    warnings,
                    f"while condition"
                )

                sub_steps = step.get("do") or step.get("steps", [])
                self._check_steps_variables(
                    sub_steps,
                    dict(defined_vars),
                    errors,
                    warnings,
                    loop_vars
                )

            else:
                # Agent step
                agent_type = step.get("agent") or step.get("agent_type")

                self._check_var_references_typed(
                    step.get("inputs", {}),
                    defined_vars,
                    loop_vars,
                    errors,
                    warnings,
                    f"step '{step_id}' inputs"
                )

                if "condition" in step:
                    self._check_var_references_typed(
                        step["condition"],
                        defined_vars,
                        loop_vars,
                        errors,
                        warnings,
                        f"step '{step_id}' condition"
                    )

                # Add outputs to defined vars with type info
                outputs = step.get("outputs") or {}
                for output_key, var_name in outputs.items():
                    if isinstance(var_name, str):
                        var_type = AGENT_OUTPUT_TYPES.get(agent_type, "any")
                        defined_vars[var_name] = VariableInfo(
                            name=var_name,
                            var_type=var_type,
                            defined_at=step_id,
                            agent_type=agent_type
                        )

                        # Warn about text_agent output type uncertainty
                        if agent_type == "text_agent":
                            warnings.append(
                                f"Variable '{var_name}' from text_agent (step '{step_id}'): "
                                f"LLM may return scalar in 'result'. "
                                f"Property access like '{{{{{var_name}.field}}}}' may fail."
                            )

                # v1 control flow (agent_type: foreach)
                if agent_type == "foreach":
                    item_var = step.get("item_var", "item")
                    index_var = step.get("index_var", "index")
                    source = step.get("source", "")

                    self._check_var_references_typed(
                        {"source": source},
                        defined_vars,
                        loop_vars,
                        errors,
                        warnings,
                        f"step '{step_id}' foreach source"
                    )

                    new_loop_vars = dict(loop_vars)
                    new_loop_vars[item_var] = VariableInfo(
                        name=item_var, var_type="loop_item", defined_at=f"loop:{step_id}"
                    )
                    new_loop_vars[index_var] = VariableInfo(
                        name=index_var, var_type="scalar", defined_at=f"loop:{step_id}"
                    )

                    if "steps" in step:
                        self._check_steps_variables(
                            step["steps"],
                            dict(defined_vars),
                            errors,
                            warnings,
                            new_loop_vars
                        )

                if "then_steps" in step:
                    self._check_steps_variables(
                        step["then_steps"],
                        dict(defined_vars),
                        errors,
                        warnings,
                        loop_vars
                    )
                if "else_steps" in step:
                    self._check_steps_variables(
                        step["else_steps"],
                        dict(defined_vars),
                        errors,
                        warnings,
                        loop_vars
                    )

    def _extract_base_var(self, text: str) -> Optional[str]:
        """Extract the base variable name from a reference like {{var.field}}"""
        match = re.search(r'\{\{(\w+)', text)
        return match.group(1) if match else None

    def _check_var_references_typed(
        self,
        obj: Any,
        defined_vars: Dict[str, VariableInfo],
        loop_vars: Dict[str, VariableInfo],
        errors: List[str],
        warnings: List[str],
        context: str
    ):
        """Check variable references with type-based property access validation"""
        if isinstance(obj, str):
            # Extract full variable references including path
            # Pattern: {{var}} or {{var.field}} or {{var.0.field}}
            pattern = r'\{\{([^}]+)\}\}'
            matches = re.findall(pattern, obj)

            for match in matches:
                match = match.strip()
                parts = match.split(".")
                base_var = parts[0]
                path_parts = parts[1:] if len(parts) > 1 else []

                # Check if variable is defined
                all_vars = {**defined_vars, **loop_vars}
                if base_var not in all_vars:
                    errors.append(
                        f"Undefined variable '{{{{{base_var}}}}}' referenced in {context}"
                    )
                    continue

                # Validate property access based on type
                if path_parts:
                    var_info = all_vars[base_var]
                    self._validate_property_access(
                        base_var, path_parts, var_info, errors, warnings, context
                    )
        elif isinstance(obj, dict):
            for value in obj.values():
                self._check_var_references_typed(value, defined_vars, loop_vars, errors, warnings, context)
        elif isinstance(obj, list):
            for item in obj:
                self._check_var_references_typed(item, defined_vars, loop_vars, errors, warnings, context)

    def _validate_property_access(
        self,
        base_var: str,
        path_parts: List[str],
        var_info: VariableInfo,
        errors: List[str],
        warnings: List[str],
        context: str
    ):
        """Validate property access based on inferred variable type"""
        var_type = var_info.var_type
        first_part = path_parts[0] if path_parts else None
        full_path = f"{base_var}.{'.'.join(path_parts)}"

        if var_type == "scalar":
            # Scalar types (bool, int, str) do not support property access
            errors.append(
                f"Cannot access property '{first_part}' on variable '{base_var}' "
                f"(type: scalar, defined at: {var_info.defined_at}) in {context}. "
                f"Scalar types do not support property access."
            )

        elif var_type == "list":
            # List supports .0, .length, .0.field
            if first_part == "length":
                pass  # OK
            elif first_part and first_part.isdigit():
                pass  # OK - index access like .0
            elif first_part and not first_part.isdigit():
                # Accessing field directly on list without index
                warnings.append(
                    f"Accessing '{full_path}' on list variable '{base_var}' in {context}: "
                    f"use index like '{{{{{base_var}.0.{first_part}}}}}' to access item fields."
                )

        elif var_type == "any":
            # Could be anything - warn about potential issues for text_agent
            if var_info.agent_type == "text_agent":
                warnings.append(
                    f"Accessing '{full_path}' on text_agent output '{base_var}' in {context}: "
                    f"may fail if LLM returns scalar instead of dict. "
                    f"Use '{{{{{base_var}}}}}' directly if expecting bool/int/str."
                )

        elif var_type == "dict":
            # Check if field is known for this agent type
            known_fields = AGENT_KNOWN_FIELDS.get(var_info.agent_type, set())
            if known_fields and first_part and first_part not in known_fields:
                known_str = ", ".join(sorted(known_fields))
                warnings.append(
                    f"Accessing unknown field '{first_part}' on '{base_var}' "
                    f"({var_info.agent_type}) in {context}. Known fields: {known_str}"
                )

        elif var_type == "loop_item":
            # Loop items are typically dict, property access is usually fine
            pass

    def _check_control_flow_structure(self, workflow: Dict) -> List[str]:
        """Check control flow structures have required fields"""
        errors = []
        steps = workflow.get("steps", [])

        def check_steps(steps: List[Dict], path: str = "steps"):
            for i, step in enumerate(steps):
                step_path = f"{path}[{i}]"
                step_id = step.get("id", f"index_{i}")

                # v2 control flow syntax
                if "foreach" in step:
                    sub_steps = step.get("do") or step.get("steps")
                    if not sub_steps:
                        errors.append(
                            f"foreach at {step_path} missing 'do' or 'steps' field"
                        )
                    else:
                        check_steps(sub_steps, f"{step_path}.do")

                elif "if" in step:
                    if "then" not in step:
                        errors.append(
                            f"if at {step_path} missing required 'then' field"
                        )
                    else:
                        check_steps(step["then"], f"{step_path}.then")
                    if "else" in step:
                        check_steps(step["else"], f"{step_path}.else")

                elif "while" in step:
                    sub_steps = step.get("do") or step.get("steps")
                    if not sub_steps:
                        errors.append(
                            f"while at {step_path} missing 'do' or 'steps' field"
                        )
                    else:
                        check_steps(sub_steps, f"{step_path}.do")

                else:
                    # v1 control flow
                    agent_type = step.get("agent") or step.get("agent_type")

                    if agent_type == "foreach":
                        if "source" not in step:
                            errors.append(
                                f"foreach step '{step_id}' at {step_path} missing 'source' field"
                            )
                        if "steps" not in step:
                            errors.append(
                                f"foreach step '{step_id}' at {step_path} missing 'steps' field"
                            )
                        else:
                            check_steps(step["steps"], f"{step_path}.steps")

                    elif agent_type == "if":
                        if "condition" not in step:
                            errors.append(
                                f"if step '{step_id}' at {step_path} missing 'condition' field"
                            )
                        if "then" not in step and "then_steps" not in step:
                            errors.append(
                                f"if step '{step_id}' at {step_path} missing 'then' field"
                            )
                        if "then" in step:
                            check_steps(step["then"], f"{step_path}.then")
                        if "then_steps" in step:
                            check_steps(step["then_steps"], f"{step_path}.then_steps")
                        if "else" in step:
                            check_steps(step["else"], f"{step_path}.else")
                        if "else_steps" in step:
                            check_steps(step["else_steps"], f"{step_path}.else_steps")

                    elif agent_type == "while":
                        if "condition" not in step:
                            errors.append(
                                f"while step '{step_id}' at {step_path} missing 'condition' field"
                            )
                        if "steps" not in step:
                            errors.append(
                                f"while step '{step_id}' at {step_path} missing 'steps' field"
                            )
                        else:
                            check_steps(step["steps"], f"{step_path}.steps")

        check_steps(steps)
        return errors

    def _check_agent_specific_fields(self, workflow: Dict) -> List[str]:
        """Check agent-specific required fields using INPUT_SCHEMA or fallback"""
        errors = []
        steps = workflow.get("steps", [])

        def check_steps(steps: List[Dict], path: str = "steps"):
            for i, step in enumerate(steps):
                step_path = f"{path}[{i}]"
                step_id = step.get("id", f"index_{i}")

                # Skip v2 control flow
                if any(key in step for key in CONTROL_FLOW_KEYS):
                    if "foreach" in step:
                        sub_steps = step.get("do") or step.get("steps", [])
                        check_steps(sub_steps, f"{step_path}.do")
                    elif "if" in step:
                        if "then" in step:
                            check_steps(step["then"], f"{step_path}.then")
                        if "else" in step:
                            check_steps(step["else"], f"{step_path}.else")
                    elif "while" in step:
                        sub_steps = step.get("do") or step.get("steps", [])
                        check_steps(sub_steps, f"{step_path}.do")
                    continue

                agent_type = step.get("agent") or step.get("agent_type")
                step_inputs = step.get("inputs", {})

                # Use INPUT_SCHEMA if available, otherwise use fallback
                if AGENT_SCHEMAS_AVAILABLE and agent_type in AGENT_SCHEMAS:
                    schema = AGENT_SCHEMAS[agent_type]
                    input_errors = self._validate_inputs_against_schema(
                        agent_type, step_inputs, schema, step_id, step_path
                    )
                    errors.extend(input_errors)
                elif agent_type in AGENT_SPECIFIC_FIELDS:
                    # Fallback to hardcoded fields
                    field_config = AGENT_SPECIFIC_FIELDS[agent_type]

                    for f in field_config.get("step", []):
                        if f not in step:
                            errors.append(
                                f"Step '{step_id}' ({agent_type}) at {step_path} missing required '{f}' field"
                            )

                    for f in field_config.get("inputs", []):
                        if f not in step_inputs:
                            errors.append(
                                f"Step '{step_id}' ({agent_type}) at {step_path} missing required 'inputs.{f}' field"
                            )

                if "steps" in step:
                    check_steps(step["steps"], f"{step_path}.steps")
                if "then" in step:
                    check_steps(step["then"], f"{step_path}.then")
                if "then_steps" in step:
                    check_steps(step["then_steps"], f"{step_path}.then_steps")
                if "else" in step:
                    check_steps(step["else"], f"{step_path}.else")
                if "else_steps" in step:
                    check_steps(step["else_steps"], f"{step_path}.else_steps")

        check_steps(steps)
        return errors

    def _validate_inputs_against_schema(
        self,
        agent_type: str,
        inputs: Dict[str, Any],
        schema: Any,
        step_id: str,
        step_path: str
    ) -> List[str]:
        """Validate inputs against INPUT_SCHEMA"""
        errors = []

        for field_name, field_schema in schema.fields.items():
            value = inputs.get(field_name)

            # Check if field is required
            is_required = field_schema.required

            # Check conditional required (e.g., "operation == 'store'")
            if field_schema.required_when:
                is_required = self._evaluate_required_condition(
                    field_schema.required_when, inputs
                )

            # Skip validation for template variables like "{{var}}"
            if value is not None and isinstance(value, str) and "{{" in value:
                continue

            if is_required and value is None:
                errors.append(
                    f"Step '{step_id}' ({agent_type}) at {step_path} missing required 'inputs.{field_name}' field"
                )

            # Check enum values (skip template variables)
            if value is not None and field_schema.enum:
                if not isinstance(value, str) or "{{" not in value:
                    if value not in field_schema.enum:
                        errors.append(
                            f"Step '{step_id}' ({agent_type}) at {step_path}: invalid value '{value}' for 'inputs.{field_name}', must be one of {field_schema.enum}"
                        )

        return errors

    def _evaluate_required_condition(self, condition: str, inputs: Dict[str, Any]) -> bool:
        """Evaluate a required_when condition like 'operation == store'"""
        match = re.match(r"(\w+)\s*(==|!=)\s*['\"]?([^'\"]+)['\"]?", condition)
        if not match:
            return False

        field, operator, expected = match.groups()
        actual = inputs.get(field)

        # Skip if actual value is a template variable
        if isinstance(actual, str) and "{{" in actual:
            return False  # Can't evaluate, assume not required

        if operator == "==":
            return actual == expected
        elif operator == "!=":
            return actual != expected

        return False

    def _check_unique_step_ids(self, workflow: Dict) -> List[str]:
        """Check all step IDs are unique"""
        errors = []
        seen_ids: Set[str] = set()
        steps = workflow.get("steps", [])

        def collect_ids(steps: List[Dict], path: str = "steps"):
            for i, step in enumerate(steps):
                step_id = step.get("id")
                step_path = f"{path}[{i}]"

                if step_id:
                    if step_id in seen_ids:
                        errors.append(f"Duplicate step id '{step_id}' at {step_path}")
                    else:
                        seen_ids.add(step_id)

                for key in ["steps", "do", "then", "else", "then_steps", "else_steps"]:
                    if key in step and isinstance(step[key], list):
                        collect_ids(step[key], f"{step_path}.{key}")

        collect_ids(steps)
        return errors


# Singleton validator instance
_validator = RuleValidator()


def validate_workflow_yaml(yaml_content: str) -> str:
    """
    Validate workflow YAML content.

    This is the main entry point for Claude Agent to use as a tool.

    Args:
        yaml_content: Workflow YAML string

    Returns:
        Human-readable validation result string
    """
    try:
        workflow = yaml.safe_load(yaml_content)
    except yaml.YAMLError as e:
        return f"YAML parse error: {e}"

    if not isinstance(workflow, dict):
        return "Invalid workflow: expected a YAML dictionary/object"

    result = _validator.validate(workflow)
    return result.to_string()


def validate_workflow_dict(workflow: Dict[str, Any]) -> ValidationResult:
    """
    Validate workflow dictionary (for programmatic use).

    Args:
        workflow: Parsed workflow dictionary

    Returns:
        ValidationResult object
    """
    if not isinstance(workflow, dict):
        return ValidationResult(
            valid=False,
            errors=[f"Invalid workflow type: expected dict, got {type(workflow).__name__}"]
        )
    return _validator.validate(workflow)
