"""
Workflow Validation Tool

Provides rule-based validation for generated workflows.
This is used by Claude Agent as a tool to check workflow correctness.

Validation rules are aligned with BaseApp's workflow_loader.py to ensure
workflows generated by Cloud Backend can be executed by BaseApp.
"""

import re
import yaml
from typing import Dict, List, Any, Set, Tuple
from dataclasses import dataclass, field
import logging

logger = logging.getLogger(__name__)

# Valid agent types (must match BaseApp's supported types)
# See: agent_workflow_engine.py _register_builtin_agents()
VALID_AGENT_TYPES = {
    "browser_agent",
    "scraper_agent",
    "storage_agent",
    "variable",
    "foreach",
    "if",
    "while",
    "text_agent",
    "code_agent",
    "tool_agent",
    "autonomous_browser_agent",
}

# Required fields at different levels
REQUIRED_ROOT_FIELDS = ["apiVersion", "kind", "metadata", "steps"]
REQUIRED_METADATA_FIELDS = ["name", "description"]
REQUIRED_STEP_FIELDS = ["id", "name", "agent_type"]  # Every step must have these

# Agent-specific required fields (aligned with BaseApp)
# Format: { agent_type: { "step": [...], "inputs": [...] } }
# - "step": fields required at step level
# - "inputs": fields required inside step.inputs
AGENT_SPECIFIC_FIELDS = {
    "code_agent": {"step": ["code"], "inputs": []},
    "text_agent": {"step": [], "inputs": ["instruction"]},  # instruction is inside inputs
    "variable": {"step": [], "inputs": []},
    "scraper_agent": {"step": [], "inputs": []},
    "browser_agent": {"step": [], "inputs": []},
    "storage_agent": {"step": [], "inputs": []},
    "tool_agent": {"step": [], "inputs": []},
    "foreach": {"step": ["source", "steps"], "inputs": []},
    "if": {"step": ["condition", "then"], "inputs": []},
    "while": {"step": ["condition", "steps"], "inputs": []},
}


@dataclass
class ValidationResult:
    """Result of workflow validation"""
    valid: bool
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "valid": self.valid,
            "errors": self.errors,
            "warnings": self.warnings
        }

    def to_string(self) -> str:
        """Convert to human-readable string for Claude Agent"""
        if self.valid and not self.warnings:
            return "Validation passed. No errors or warnings."

        parts = []
        if not self.valid:
            parts.append("VALIDATION FAILED")
            parts.append(f"Errors ({len(self.errors)}):")
            for i, error in enumerate(self.errors, 1):
                parts.append(f"  {i}. {error}")

        if self.warnings:
            parts.append(f"Warnings ({len(self.warnings)}):")
            for i, warning in enumerate(self.warnings, 1):
                parts.append(f"  {i}. {warning}")

        if self.valid:
            parts.insert(0, "Validation passed with warnings.")

        return "\n".join(parts)


class RuleValidator:
    """Rule-based workflow validator"""

    def validate(self, workflow: Dict[str, Any]) -> ValidationResult:
        """
        Validate a workflow dictionary.

        Args:
            workflow: Parsed workflow dictionary

        Returns:
            ValidationResult with errors and warnings
        """
        errors = []
        warnings = []

        # 1. Check required root fields
        errors.extend(self._check_required_fields(workflow))

        # 2. Check metadata fields
        if "metadata" in workflow:
            errors.extend(self._check_metadata(workflow["metadata"]))

        # 3. Check step required fields (id, name, agent_type)
        errors.extend(self._check_step_required_fields(workflow))

        # 4. Check agent types
        errors.extend(self._check_agent_types(workflow))

        # 5. Check variable references
        var_errors, var_warnings = self._check_variables(workflow)
        errors.extend(var_errors)
        warnings.extend(var_warnings)

        # 5. Check control flow structures (foreach, if, while)
        errors.extend(self._check_control_flow_structure(workflow))

        # 6. Check agent-specific required fields
        errors.extend(self._check_agent_specific_fields(workflow))

        # 7. Check step IDs are unique
        errors.extend(self._check_unique_step_ids(workflow))

        # 8. Check final_response requirement
        fr_errors, fr_warnings = self._check_final_response(workflow)
        errors.extend(fr_errors)
        warnings.extend(fr_warnings)

        return ValidationResult(
            valid=len(errors) == 0,
            errors=errors,
            warnings=warnings
        )

    def _check_required_fields(self, workflow: Dict) -> List[str]:
        """Check required root fields"""
        errors = []
        for field in REQUIRED_ROOT_FIELDS:
            if field not in workflow:
                errors.append(f"Missing required field: '{field}'")
        return errors

    def _check_metadata(self, metadata: Dict) -> List[str]:
        """Check metadata fields"""
        errors = []
        for field in REQUIRED_METADATA_FIELDS:
            if field not in metadata:
                errors.append(f"Missing required field: 'metadata.{field}'")
        return errors

    def _check_step_required_fields(self, workflow: Dict) -> List[str]:
        """Check every step has required fields: id, name, agent_type"""
        errors = []
        steps = workflow.get("steps", [])

        def check_steps(steps: List[Dict], path: str = "steps"):
            for i, step in enumerate(steps):
                step_path = f"{path}[{i}]"
                step_id = step.get("id", f"<unnamed at {step_path}>")

                for field in REQUIRED_STEP_FIELDS:
                    if field not in step:
                        errors.append(
                            f"Step '{step_id}' at {step_path} missing required field '{field}'"
                        )

                # Check nested steps in foreach
                if "steps" in step:
                    check_steps(step["steps"], f"{step_path}.steps")

                # Check nested steps in if/while
                if "then" in step:
                    check_steps(step["then"], f"{step_path}.then")
                if "then_steps" in step:
                    check_steps(step["then_steps"], f"{step_path}.then_steps")
                if "else" in step:
                    check_steps(step["else"], f"{step_path}.else")
                if "else_steps" in step:
                    check_steps(step["else_steps"], f"{step_path}.else_steps")

        check_steps(steps)
        return errors

    def _check_agent_types(self, workflow: Dict) -> List[str]:
        """Check agent types are valid"""
        errors = []
        steps = workflow.get("steps", [])

        def check_steps(steps: List[Dict], path: str = "steps"):
            for i, step in enumerate(steps):
                step_path = f"{path}[{i}]"
                step_id = step.get("id", f"index_{i}")

                agent_type = step.get("agent_type")
                if agent_type is None:
                    # Check if it's a control flow step (if/while)
                    if "control_type" not in step:
                        errors.append(f"Step '{step_id}' at {step_path} missing 'agent_type'")
                elif agent_type not in VALID_AGENT_TYPES:
                    errors.append(
                        f"Invalid agent_type '{agent_type}' at step '{step_id}'. "
                        f"Valid types: {', '.join(sorted(VALID_AGENT_TYPES))}"
                    )

                # Check nested steps in foreach
                if agent_type == "foreach" and "steps" in step:
                    check_steps(step["steps"], f"{step_path}.steps")

                # Check nested steps in if/while
                if "then_steps" in step:
                    check_steps(step["then_steps"], f"{step_path}.then_steps")
                if "else_steps" in step:
                    check_steps(step["else_steps"], f"{step_path}.else_steps")

        check_steps(steps)
        return errors

    def _check_variables(self, workflow: Dict) -> Tuple[List[str], List[str]]:
        """Check variable references have definitions"""
        errors = []
        warnings = []

        # Collect defined variables
        defined_vars: Set[str] = set()

        # Add workflow inputs as predefined variables
        workflow_inputs = workflow.get("inputs", {})
        if isinstance(workflow_inputs, dict):
            for var_name in workflow_inputs.keys():
                defined_vars.add(var_name)

        # Process steps
        steps = workflow.get("steps", [])
        self._check_steps_variables(steps, defined_vars, errors, warnings, set())

        return errors, warnings

    def _check_steps_variables(
        self,
        steps: List[Dict],
        defined_vars: Set[str],
        errors: List[str],
        warnings: List[str],
        loop_vars: Set[str]
    ):
        """Recursively check variables in steps"""
        for step in steps:
            step_id = step.get("id", "unknown")
            agent_type = step.get("agent_type")

            # Check variable references in inputs
            self._check_var_references(
                step.get("inputs", {}),
                defined_vars | loop_vars,
                errors,
                f"step '{step_id}' inputs"
            )

            # Check variable references in condition
            if "condition" in step:
                self._check_var_references(
                    step["condition"],
                    defined_vars | loop_vars,
                    errors,
                    f"step '{step_id}' condition"
                )

            # Collect outputs as new defined variables
            for var_name in step.get("outputs", {}).values():
                if isinstance(var_name, str):
                    defined_vars.add(var_name)

            # Handle foreach loops
            if agent_type == "foreach":
                item_var = step.get("item_var", "item")
                index_var = step.get("index_var", "index")
                source = step.get("source", "")

                # Check source reference
                self._check_var_references(
                    {"source": source},
                    defined_vars | loop_vars,
                    errors,
                    f"step '{step_id}' foreach source"
                )

                # Check nested steps with loop variables
                new_loop_vars = loop_vars | {item_var, index_var}
                if "steps" in step:
                    self._check_steps_variables(
                        step["steps"],
                        defined_vars.copy(),  # Copy to avoid pollution
                        errors,
                        warnings,
                        new_loop_vars
                    )

            # Handle if/while
            if "then_steps" in step:
                self._check_steps_variables(
                    step["then_steps"],
                    defined_vars.copy(),
                    errors,
                    warnings,
                    loop_vars
                )
            if "else_steps" in step:
                self._check_steps_variables(
                    step["else_steps"],
                    defined_vars.copy(),
                    errors,
                    warnings,
                    loop_vars
                )

    def _check_var_references(
        self,
        obj: Any,
        defined_vars: Set[str],
        errors: List[str],
        context: str
    ):
        """Check variable references in an object"""
        if isinstance(obj, str):
            # Find {{var}} or {{var.field}} or {{var.0.field}} patterns
            refs = re.findall(r'\{\{(\w+)(?:[\.\[\]\w]*)*\}\}', obj)
            for var_name in refs:
                if var_name not in defined_vars:
                    errors.append(
                        f"Undefined variable '{{{{{{{{}}}}}}}}' referenced in {context}".format(var_name)
                    )
        elif isinstance(obj, dict):
            for value in obj.values():
                self._check_var_references(value, defined_vars, errors, context)
        elif isinstance(obj, list):
            for item in obj:
                self._check_var_references(item, defined_vars, errors, context)

    def _check_control_flow_structure(self, workflow: Dict) -> List[str]:
        """Check control flow structures (foreach, if, while) have required fields"""
        errors = []
        steps = workflow.get("steps", [])

        def check_steps(steps: List[Dict], path: str = "steps"):
            for i, step in enumerate(steps):
                step_path = f"{path}[{i}]"
                step_id = step.get("id", f"index_{i}")
                agent_type = step.get("agent_type")

                # Check foreach structure
                if agent_type == "foreach":
                    if "source" not in step:
                        errors.append(
                            f"foreach step '{step_id}' at {step_path} missing required 'source' field"
                        )
                    if "steps" not in step:
                        errors.append(
                            f"foreach step '{step_id}' at {step_path} missing required 'steps' field"
                        )
                    else:
                        check_steps(step["steps"], f"{step_path}.steps")

                # Check if structure
                elif agent_type == "if":
                    if "condition" not in step:
                        errors.append(
                            f"if step '{step_id}' at {step_path} missing required 'condition' field"
                        )
                    if "then" not in step and "then_steps" not in step:
                        errors.append(
                            f"if step '{step_id}' at {step_path} missing required 'then' field"
                        )
                    # Check nested steps
                    if "then" in step:
                        check_steps(step["then"], f"{step_path}.then")
                    if "then_steps" in step:
                        check_steps(step["then_steps"], f"{step_path}.then_steps")
                    if "else" in step:
                        check_steps(step["else"], f"{step_path}.else")
                    if "else_steps" in step:
                        check_steps(step["else_steps"], f"{step_path}.else_steps")

                # Check while structure
                elif agent_type == "while":
                    if "condition" not in step:
                        errors.append(
                            f"while step '{step_id}' at {step_path} missing required 'condition' field"
                        )
                    if "steps" not in step:
                        errors.append(
                            f"while step '{step_id}' at {step_path} missing required 'steps' field"
                        )
                    else:
                        check_steps(step["steps"], f"{step_path}.steps")

        check_steps(steps)
        return errors

    def _check_agent_specific_fields(self, workflow: Dict) -> List[str]:
        """Check agent-specific required fields"""
        errors = []
        steps = workflow.get("steps", [])

        def check_steps(steps: List[Dict], path: str = "steps"):
            for i, step in enumerate(steps):
                step_path = f"{path}[{i}]"
                step_id = step.get("id", f"index_{i}")
                agent_type = step.get("agent_type")

                if agent_type in AGENT_SPECIFIC_FIELDS:
                    field_config = AGENT_SPECIFIC_FIELDS[agent_type]

                    # Check step-level required fields
                    for field in field_config.get("step", []):
                        if field not in step:
                            errors.append(
                                f"Step '{step_id}' ({agent_type}) at {step_path} missing required '{field}' field"
                            )

                    # Check inputs-level required fields
                    step_inputs = step.get("inputs", {})
                    for field in field_config.get("inputs", []):
                        if field not in step_inputs:
                            errors.append(
                                f"Step '{step_id}' ({agent_type}) at {step_path} missing required 'inputs.{field}' field"
                            )

                # Recursively check nested steps
                if "steps" in step:
                    check_steps(step["steps"], f"{step_path}.steps")
                if "then" in step:
                    check_steps(step["then"], f"{step_path}.then")
                if "then_steps" in step:
                    check_steps(step["then_steps"], f"{step_path}.then_steps")
                if "else" in step:
                    check_steps(step["else"], f"{step_path}.else")
                if "else_steps" in step:
                    check_steps(step["else_steps"], f"{step_path}.else_steps")

        check_steps(steps)
        return errors

    def _check_final_response(self, workflow: Dict) -> Tuple[List[str], List[str]]:
        """Check workflow has at least one step outputting final_response"""
        errors = []
        warnings = []
        steps = workflow.get("steps", [])

        def has_final_response(steps: List[Dict]) -> bool:
            for step in steps:
                outputs = step.get("outputs", {})
                if isinstance(outputs, dict):
                    if "final_response" in outputs.values():
                        return True

                # Check nested steps
                if "steps" in step and has_final_response(step["steps"]):
                    return True
                if "then" in step and has_final_response(step["then"]):
                    return True
                if "then_steps" in step and has_final_response(step["then_steps"]):
                    return True
                if "else" in step and has_final_response(step["else"]):
                    return True
                if "else_steps" in step and has_final_response(step["else_steps"]):
                    return True

            return False

        if not has_final_response(steps):
            warnings.append(
                "No step outputs 'final_response'. Workflow may not return a result. "
                "Consider adding 'outputs: {result: final_response}' to the last step."
            )

        return errors, warnings

    def _check_unique_step_ids(self, workflow: Dict) -> List[str]:
        """Check all step IDs are unique"""
        errors = []
        seen_ids: Set[str] = set()
        steps = workflow.get("steps", [])

        def collect_ids(steps: List[Dict], path: str = "steps"):
            for i, step in enumerate(steps):
                step_id = step.get("id")
                step_path = f"{path}[{i}]"

                if step_id:
                    if step_id in seen_ids:
                        errors.append(f"Duplicate step id '{step_id}' at {step_path}")
                    else:
                        seen_ids.add(step_id)

                # Check nested steps
                if "steps" in step:
                    collect_ids(step["steps"], f"{step_path}.steps")
                if "then_steps" in step:
                    collect_ids(step["then_steps"], f"{step_path}.then_steps")
                if "else_steps" in step:
                    collect_ids(step["else_steps"], f"{step_path}.else_steps")

        collect_ids(steps)
        return errors


# Singleton validator instance
_validator = RuleValidator()


def validate_workflow_yaml(yaml_content: str) -> str:
    """
    Validate workflow YAML content.

    This is the main entry point for Claude Agent to use as a tool.

    Args:
        yaml_content: Workflow YAML string

    Returns:
        Human-readable validation result string
    """
    try:
        workflow = yaml.safe_load(yaml_content)
    except yaml.YAMLError as e:
        return f"YAML parse error: {e}"

    if not isinstance(workflow, dict):
        return "Invalid workflow: expected a YAML dictionary/object"

    result = _validator.validate(workflow)
    return result.to_string()


def validate_workflow_dict(workflow: Dict[str, Any]) -> ValidationResult:
    """
    Validate workflow dictionary (for programmatic use).

    Args:
        workflow: Parsed workflow dictionary

    Returns:
        ValidationResult object
    """
    # Type check: workflow must be a dict
    if not isinstance(workflow, dict):
        return ValidationResult(
            valid=False,
            errors=[f"Invalid workflow type: expected dict, got {type(workflow).__name__}"]
        )
    return _validator.validate(workflow)
