"""CognitivePhrase module - Cognitive phrase composed of States and Actions.

CognitivePhrase represents a cognitive phrase composed of multiple State
and Action units.
"""

import uuid
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field
from pydantic import model_validator


class CognitivePhrase(BaseModel):
    """CognitivePhrase - Cognitive phrase.

    Represents a cognitive phrase composed of multiple State and Action units.
    This is a higher-level semantic abstraction, representing the process
    of a user completing a complete task or goal.

    Attributes:
        id: Unique cognitive phrase identifier (auto-generated if not
            provided).
        label: Cognitive phrase label.
        description: Cognitive phrase description (optional).
        start_timestamp: Start timestamp in milliseconds.
        end_timestamp: End timestamp in milliseconds (optional).
        duration: Duration in milliseconds (optional).
        user_id: User ID (optional).
        session_id: Session ID (optional).
        goal_id: Associated user goal ID (optional).
        goal_description: Goal description (optional).
        states: List of contained States.
        state_ids: List of State IDs (optional).
        actions: List of contained Actions.
        attributes: Cognitive phrase attributes.
        embedding_vector: Vector representation for retrieval (optional).
        llm_generated: Whether generated by LLM.
        confidence_score: Confidence score (optional).
    """

    # Core identifiers
    id: Optional[str] = Field(
        default=None, description='Unique cognitive phrase identifier')
    label: str = Field(..., description='Cognitive phrase label')
    description: Optional[str] = Field(
        default=None, description='Cognitive phrase description')

    # Time information
    start_timestamp: int = Field(
        ..., description='Start timestamp in milliseconds')
    end_timestamp: Optional[int] = Field(
        default=None, description='End timestamp in milliseconds')
    duration: Optional[int] = Field(
        default=None, description='Duration in milliseconds')

    # User session information
    user_id: Optional[str] = Field(default=None, description='User ID')
    session_id: Optional[str] = Field(default=None, description='Session ID')

    # Associated user goal
    goal_id: Optional[str] = Field(
        default=None, description='Associated user goal ID')
    goal_description: Optional[str] = Field(
        default=None, description='Goal description')

    # Composed elements
    states: List[Any] = Field(
        default_factory=list, description='List of contained States')
    state_ids: Optional[List[str]] = Field(
        default=None, description='List of State IDs')
    actions: List[Any] = Field(
        default_factory=list, description='List of contained Actions')

    # Semantic attributes
    attributes: Dict[str, Any] = Field(
        default_factory=dict, description='Cognitive phrase attributes')

    # Vector representation (for retrieval)
    embedding_vector: Optional[List[float]] = Field(
        default=None, description='Vector representation')

    # LLM related
    llm_generated: bool = Field(
        default=False, description='Whether generated by LLM')
    confidence_score: Optional[float] = Field(
        default=None, description='Confidence score', ge=0.0, le=1.0)

    @model_validator(mode='before')
    @classmethod
    def generate_id(cls, data: Any) -> Any:
        """Auto-generate ID if not provided.

        Args:
            data: Input data dictionary.

        Returns:
            Data with ID generated if missing.
        """
        if isinstance(data, dict):
            if not data.get('id'):
                data['id'] = str(uuid.uuid4())
        return data

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary.

        Returns:
            Dictionary representation of the cognitive phrase.
        """
        data = self.model_dump()
        # Handle states
        if self.states:
            data['states'] = [
                state.to_dict() if hasattr(state, 'to_dict') else state
                for state in self.states
            ]
        # Handle actions
        if self.actions:
            data['actions'] = [
                action.to_dict() if hasattr(action, 'to_dict') else action
                for action in self.actions
            ]
        return data

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'CognitivePhrase':
        """Create instance from dictionary.

        Args:
            data: Dictionary containing cognitive phrase data.

        Returns:
            CognitivePhrase instance.
        """
        return cls(**data)


__all__ = [
    'CognitivePhrase',
]
